package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Cardphonelimit;
import com.csii.upp.dto.generate.CardphonelimitExample;

public class CardphonelimitDAO extends BasePayDAO{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int countByExample(CardphonelimitExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("CARDPHONELIMIT.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int deleteByExample(CardphonelimitExample example) throws SQLException {
        int rows = getSqlMap().delete("CARDPHONELIMIT.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String cardnbr, String mobile, Date dealdate) throws SQLException {
        Cardphonelimit _key = new Cardphonelimit();
        _key.setCardnbr(cardnbr);
        _key.setMobile(mobile);
        _key.setDealdate(dealdate);
        int rows = getSqlMap().delete("CARDPHONELIMIT.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static void insert(Cardphonelimit record) throws SQLException {
        getSqlMap().insert("CARDPHONELIMIT.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static void insertSelective(Cardphonelimit record) throws SQLException {
        getSqlMap().insert("CARDPHONELIMIT.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Cardphonelimit> selectByExample(CardphonelimitExample example) throws SQLException {
        List<Cardphonelimit> list = getSqlMap().queryForList("CARDPHONELIMIT.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static Cardphonelimit selectByPrimaryKey(String cardnbr, String mobile, Date dealdate) throws SQLException {
        Cardphonelimit _key = new Cardphonelimit();
        _key.setCardnbr(cardnbr);
        _key.setMobile(mobile);
        _key.setDealdate(dealdate);
        Cardphonelimit record = (Cardphonelimit) getSqlMap().queryForObject("CARDPHONELIMIT.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Cardphonelimit record, CardphonelimitExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("CARDPHONELIMIT.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int updateByExample(Cardphonelimit record, CardphonelimitExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("CARDPHONELIMIT.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Cardphonelimit record) throws SQLException {
        int rows = getSqlMap().update("CARDPHONELIMIT.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Cardphonelimit record) throws SQLException {
        int rows = getSqlMap().update("CARDPHONELIMIT.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CARDPHONELIMIT
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends CardphonelimitExample {
        private Object record;

        public UpdateByExampleParms(Object record, CardphonelimitExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}