package com.csii.upp.dto.generate;

import java.math.BigDecimal;
import java.util.Date;

public class Batchcleartrans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSSEQNBR
     *
     * @mbggenerated
     */
    private String transseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSDATE
     *
     * @mbggenerated
     */
    private Date transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MERSEQNBR
     *
     * @mbggenerated
     */
    private String merseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    private String downsystransnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CHANNELNBR
     *
     * @mbggenerated
     */
    private String channelnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CLEARDATE
     *
     * @mbggenerated
     */
    private Date cleardate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DOWNSYSDATE
     *
     * @mbggenerated
     */
    private Date downsysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MERTRANSDATE
     *
     * @mbggenerated
     */
    private Date mertransdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    private Date mertransdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSTYPCD
     *
     * @mbggenerated
     */
    private String transtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSCODE
     *
     * @mbggenerated
     */
    private String transcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MERNBR
     *
     * @mbggenerated
     */
    private String mernbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    private String meropendeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    private String merdevdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERACCTKIND
     *
     * @mbggenerated
     */
    private String payeracctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    private String payeeacctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CUSTCIFNBR
     *
     * @mbggenerated
     */
    private String custcifnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERACCTNBR
     *
     * @mbggenerated
     */
    private String payeracctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeraccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeracctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERACCTNAME
     *
     * @mbggenerated
     */
    private String payeracctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    private String payercardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    private String payeecardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    private String payeeacctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeeacctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeeaccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    private String payeeacctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSAMT
     *
     * @mbggenerated
     */
    private BigDecimal transamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CURRENCYCD
     *
     * @mbggenerated
     */
    private String currencycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.REFUNDEDAMT
     *
     * @mbggenerated
     */
    private BigDecimal refundedamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.UNREFUNDAMT
     *
     * @mbggenerated
     */
    private BigDecimal unrefundamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSAMT3
     *
     * @mbggenerated
     */
    private BigDecimal transamt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSAMT4
     *
     * @mbggenerated
     */
    private BigDecimal transamt4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.FEEAMT
     *
     * @mbggenerated
     */
    private BigDecimal feeamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    private String downsysrespcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.RESPCODE
     *
     * @mbggenerated
     */
    private String respcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSSTATUS
     *
     * @mbggenerated
     */
    private String transstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PROCSTEP
     *
     * @mbggenerated
     */
    private String procstep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PROCSTATUS
     *
     * @mbggenerated
     */
    private String procstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MEMO1
     *
     * @mbggenerated
     */
    private String memo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSTIME
     *
     * @mbggenerated
     */
    private Date transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.MEMO2
     *
     * @mbggenerated
     */
    private String memo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    private String departmentnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    private Date downsysdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.SYSTEMCODE
     *
     * @mbggenerated
     */
    private String systemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.TRANSMODE
     *
     * @mbggenerated
     */
    private String transmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.SIGNNBR
     *
     * @mbggenerated
     */
    private String signnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PROFITSEQNBR
     *
     * @mbggenerated
     */
    private String profitseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    private BigDecimal confirmedamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    private Long confirmedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.REFUNDMODE
     *
     * @mbggenerated
     */
    private String refundmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.INTERALAMT
     *
     * @mbggenerated
     */
    private String interalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.INTERALFLAG
     *
     * @mbggenerated
     */
    private String interalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal deductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.REALAMT
     *
     * @mbggenerated
     */
    private BigDecimal realamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    private String origmerseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.ORIGMERDATE
     *
     * @mbggenerated
     */
    private Date origmerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.ORIGSEQNBR
     *
     * @mbggenerated
     */
    private String origseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    private Date origcleardate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CHECKSTATUS
     *
     * @mbggenerated
     */
    private String checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.PAYTYPCD
     *
     * @mbggenerated
     */
    private String paytypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CYBERTYPCD
     *
     * @mbggenerated
     */
    private String cybertypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DATELASTMAINT
     *
     * @mbggenerated
     */
    private Date datelastmaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CLIENTNO
     *
     * @mbggenerated
     */
    private String clientno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.BRANCHNO
     *
     * @mbggenerated
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String pointreacctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    private String subpayeraccttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    private String subpayeracctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal unrefunddeductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal refunddeductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.RECEIPTAMT
     *
     * @mbggenerated
     */
    private BigDecimal receiptamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CODETYPCD
     *
     * @mbggenerated
     */
    private String codetypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.SCANCODEMODE
     *
     * @mbggenerated
     */
    private String scancodemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    private String qrcodeordernbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.CODEURL
     *
     * @mbggenerated
     */
    private String codeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    private BigDecimal discountableamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCHCLEARTRANS.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    private BigDecimal undiscountableamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSSEQNBR
     *
     * @return the value of BATCHCLEARTRANS.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public String getTransseqnbr() {
        return transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSSEQNBR
     *
     * @param transseqnbr the value for BATCHCLEARTRANS.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public void setTransseqnbr(String transseqnbr) {
        this.transseqnbr = transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSDATE
     *
     * @return the value of BATCHCLEARTRANS.TRANSDATE
     *
     * @mbggenerated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSDATE
     *
     * @param transdate the value for BATCHCLEARTRANS.TRANSDATE
     *
     * @mbggenerated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MERSEQNBR
     *
     * @return the value of BATCHCLEARTRANS.MERSEQNBR
     *
     * @mbggenerated
     */
    public String getMerseqnbr() {
        return merseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MERSEQNBR
     *
     * @param merseqnbr the value for BATCHCLEARTRANS.MERSEQNBR
     *
     * @mbggenerated
     */
    public void setMerseqnbr(String merseqnbr) {
        this.merseqnbr = merseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DOWNSYSTRANSNBR
     *
     * @return the value of BATCHCLEARTRANS.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public String getDownsystransnbr() {
        return downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DOWNSYSTRANSNBR
     *
     * @param downsystransnbr the value for BATCHCLEARTRANS.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public void setDownsystransnbr(String downsystransnbr) {
        this.downsystransnbr = downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CHANNELNBR
     *
     * @return the value of BATCHCLEARTRANS.CHANNELNBR
     *
     * @mbggenerated
     */
    public String getChannelnbr() {
        return channelnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CHANNELNBR
     *
     * @param channelnbr the value for BATCHCLEARTRANS.CHANNELNBR
     *
     * @mbggenerated
     */
    public void setChannelnbr(String channelnbr) {
        this.channelnbr = channelnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CLEARDATE
     *
     * @return the value of BATCHCLEARTRANS.CLEARDATE
     *
     * @mbggenerated
     */
    public Date getCleardate() {
        return cleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CLEARDATE
     *
     * @param cleardate the value for BATCHCLEARTRANS.CLEARDATE
     *
     * @mbggenerated
     */
    public void setCleardate(Date cleardate) {
        this.cleardate = cleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DOWNSYSDATE
     *
     * @return the value of BATCHCLEARTRANS.DOWNSYSDATE
     *
     * @mbggenerated
     */
    public Date getDownsysdate() {
        return downsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DOWNSYSDATE
     *
     * @param downsysdate the value for BATCHCLEARTRANS.DOWNSYSDATE
     *
     * @mbggenerated
     */
    public void setDownsysdate(Date downsysdate) {
        this.downsysdate = downsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MERTRANSDATE
     *
     * @return the value of BATCHCLEARTRANS.MERTRANSDATE
     *
     * @mbggenerated
     */
    public Date getMertransdate() {
        return mertransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MERTRANSDATE
     *
     * @param mertransdate the value for BATCHCLEARTRANS.MERTRANSDATE
     *
     * @mbggenerated
     */
    public void setMertransdate(Date mertransdate) {
        this.mertransdate = mertransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MERTRANSDATETIME
     *
     * @return the value of BATCHCLEARTRANS.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    public Date getMertransdatetime() {
        return mertransdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MERTRANSDATETIME
     *
     * @param mertransdatetime the value for BATCHCLEARTRANS.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    public void setMertransdatetime(Date mertransdatetime) {
        this.mertransdatetime = mertransdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSTYPCD
     *
     * @return the value of BATCHCLEARTRANS.TRANSTYPCD
     *
     * @mbggenerated
     */
    public String getTranstypcd() {
        return transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSTYPCD
     *
     * @param transtypcd the value for BATCHCLEARTRANS.TRANSTYPCD
     *
     * @mbggenerated
     */
    public void setTranstypcd(String transtypcd) {
        this.transtypcd = transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSCODE
     *
     * @return the value of BATCHCLEARTRANS.TRANSCODE
     *
     * @mbggenerated
     */
    public String getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSCODE
     *
     * @param transcode the value for BATCHCLEARTRANS.TRANSCODE
     *
     * @mbggenerated
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MERNBR
     *
     * @return the value of BATCHCLEARTRANS.MERNBR
     *
     * @mbggenerated
     */
    public String getMernbr() {
        return mernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MERNBR
     *
     * @param mernbr the value for BATCHCLEARTRANS.MERNBR
     *
     * @mbggenerated
     */
    public void setMernbr(String mernbr) {
        this.mernbr = mernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MEROPENDEPTNBR
     *
     * @return the value of BATCHCLEARTRANS.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    public String getMeropendeptnbr() {
        return meropendeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MEROPENDEPTNBR
     *
     * @param meropendeptnbr the value for BATCHCLEARTRANS.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    public void setMeropendeptnbr(String meropendeptnbr) {
        this.meropendeptnbr = meropendeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MERDEVDEPTNBR
     *
     * @return the value of BATCHCLEARTRANS.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    public String getMerdevdeptnbr() {
        return merdevdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MERDEVDEPTNBR
     *
     * @param merdevdeptnbr the value for BATCHCLEARTRANS.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    public void setMerdevdeptnbr(String merdevdeptnbr) {
        this.merdevdeptnbr = merdevdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERACCTKIND
     *
     * @return the value of BATCHCLEARTRANS.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeracctkind() {
        return payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERACCTKIND
     *
     * @param payeracctkind the value for BATCHCLEARTRANS.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeracctkind(String payeracctkind) {
        this.payeracctkind = payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEEACCTKIND
     *
     * @return the value of BATCHCLEARTRANS.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeeacctkind() {
        return payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEEACCTKIND
     *
     * @param payeeacctkind the value for BATCHCLEARTRANS.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeeacctkind(String payeeacctkind) {
        this.payeeacctkind = payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CUSTCIFNBR
     *
     * @return the value of BATCHCLEARTRANS.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public String getCustcifnbr() {
        return custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CUSTCIFNBR
     *
     * @param custcifnbr the value for BATCHCLEARTRANS.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public void setCustcifnbr(String custcifnbr) {
        this.custcifnbr = custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERACCTNBR
     *
     * @return the value of BATCHCLEARTRANS.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctnbr() {
        return payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERACCTNBR
     *
     * @param payeracctnbr the value for BATCHCLEARTRANS.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctnbr(String payeracctnbr) {
        this.payeracctnbr = payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERACCTTYPCD
     *
     * @return the value of BATCHCLEARTRANS.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeraccttypcd() {
        return payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERACCTTYPCD
     *
     * @param payeraccttypcd the value for BATCHCLEARTRANS.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeraccttypcd(String payeraccttypcd) {
        this.payeraccttypcd = payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERACCTDEPTNBR
     *
     * @return the value of BATCHCLEARTRANS.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctdeptnbr() {
        return payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERACCTDEPTNBR
     *
     * @param payeracctdeptnbr the value for BATCHCLEARTRANS.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctdeptnbr(String payeracctdeptnbr) {
        this.payeracctdeptnbr = payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERACCTNAME
     *
     * @return the value of BATCHCLEARTRANS.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeracctname() {
        return payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERACCTNAME
     *
     * @param payeracctname the value for BATCHCLEARTRANS.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeracctname(String payeracctname) {
        this.payeracctname = payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYERCARDTYPCD
     *
     * @return the value of BATCHCLEARTRANS.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayercardtypcd() {
        return payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYERCARDTYPCD
     *
     * @param payercardtypcd the value for BATCHCLEARTRANS.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayercardtypcd(String payercardtypcd) {
        this.payercardtypcd = payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEECARDTYPCD
     *
     * @return the value of BATCHCLEARTRANS.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayeecardtypcd() {
        return payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEECARDTYPCD
     *
     * @param payeecardtypcd the value for BATCHCLEARTRANS.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayeecardtypcd(String payeecardtypcd) {
        this.payeecardtypcd = payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEEACCTNBR
     *
     * @return the value of BATCHCLEARTRANS.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctnbr() {
        return payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEEACCTNBR
     *
     * @param payeeacctnbr the value for BATCHCLEARTRANS.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctnbr(String payeeacctnbr) {
        this.payeeacctnbr = payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEEACCTDEPTNBR
     *
     * @return the value of BATCHCLEARTRANS.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctdeptnbr() {
        return payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEEACCTDEPTNBR
     *
     * @param payeeacctdeptnbr the value for BATCHCLEARTRANS.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctdeptnbr(String payeeacctdeptnbr) {
        this.payeeacctdeptnbr = payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEEACCTTYPCD
     *
     * @return the value of BATCHCLEARTRANS.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeeaccttypcd() {
        return payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEEACCTTYPCD
     *
     * @param payeeaccttypcd the value for BATCHCLEARTRANS.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeeaccttypcd(String payeeaccttypcd) {
        this.payeeaccttypcd = payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYEEACCTNAME
     *
     * @return the value of BATCHCLEARTRANS.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeeacctname() {
        return payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYEEACCTNAME
     *
     * @param payeeacctname the value for BATCHCLEARTRANS.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeeacctname(String payeeacctname) {
        this.payeeacctname = payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSAMT
     *
     * @return the value of BATCHCLEARTRANS.TRANSAMT
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt() {
        return transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSAMT
     *
     * @param transamt the value for BATCHCLEARTRANS.TRANSAMT
     *
     * @mbggenerated
     */
    public void setTransamt(BigDecimal transamt) {
        this.transamt = transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CURRENCYCD
     *
     * @return the value of BATCHCLEARTRANS.CURRENCYCD
     *
     * @mbggenerated
     */
    public String getCurrencycd() {
        return currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CURRENCYCD
     *
     * @param currencycd the value for BATCHCLEARTRANS.CURRENCYCD
     *
     * @mbggenerated
     */
    public void setCurrencycd(String currencycd) {
        this.currencycd = currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.REFUNDEDAMT
     *
     * @return the value of BATCHCLEARTRANS.REFUNDEDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRefundedamt() {
        return refundedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.REFUNDEDAMT
     *
     * @param refundedamt the value for BATCHCLEARTRANS.REFUNDEDAMT
     *
     * @mbggenerated
     */
    public void setRefundedamt(BigDecimal refundedamt) {
        this.refundedamt = refundedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.UNREFUNDAMT
     *
     * @return the value of BATCHCLEARTRANS.UNREFUNDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUnrefundamt() {
        return unrefundamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.UNREFUNDAMT
     *
     * @param unrefundamt the value for BATCHCLEARTRANS.UNREFUNDAMT
     *
     * @mbggenerated
     */
    public void setUnrefundamt(BigDecimal unrefundamt) {
        this.unrefundamt = unrefundamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSAMT3
     *
     * @return the value of BATCHCLEARTRANS.TRANSAMT3
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt3() {
        return transamt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSAMT3
     *
     * @param transamt3 the value for BATCHCLEARTRANS.TRANSAMT3
     *
     * @mbggenerated
     */
    public void setTransamt3(BigDecimal transamt3) {
        this.transamt3 = transamt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSAMT4
     *
     * @return the value of BATCHCLEARTRANS.TRANSAMT4
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt4() {
        return transamt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSAMT4
     *
     * @param transamt4 the value for BATCHCLEARTRANS.TRANSAMT4
     *
     * @mbggenerated
     */
    public void setTransamt4(BigDecimal transamt4) {
        this.transamt4 = transamt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.FEEAMT
     *
     * @return the value of BATCHCLEARTRANS.FEEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getFeeamt() {
        return feeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.FEEAMT
     *
     * @param feeamt the value for BATCHCLEARTRANS.FEEAMT
     *
     * @mbggenerated
     */
    public void setFeeamt(BigDecimal feeamt) {
        this.feeamt = feeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DOWNSYSRESPCODE
     *
     * @return the value of BATCHCLEARTRANS.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    public String getDownsysrespcode() {
        return downsysrespcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DOWNSYSRESPCODE
     *
     * @param downsysrespcode the value for BATCHCLEARTRANS.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    public void setDownsysrespcode(String downsysrespcode) {
        this.downsysrespcode = downsysrespcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.RESPCODE
     *
     * @return the value of BATCHCLEARTRANS.RESPCODE
     *
     * @mbggenerated
     */
    public String getRespcode() {
        return respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.RESPCODE
     *
     * @param respcode the value for BATCHCLEARTRANS.RESPCODE
     *
     * @mbggenerated
     */
    public void setRespcode(String respcode) {
        this.respcode = respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSSTATUS
     *
     * @return the value of BATCHCLEARTRANS.TRANSSTATUS
     *
     * @mbggenerated
     */
    public String getTransstatus() {
        return transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSSTATUS
     *
     * @param transstatus the value for BATCHCLEARTRANS.TRANSSTATUS
     *
     * @mbggenerated
     */
    public void setTransstatus(String transstatus) {
        this.transstatus = transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PROCSTEP
     *
     * @return the value of BATCHCLEARTRANS.PROCSTEP
     *
     * @mbggenerated
     */
    public String getProcstep() {
        return procstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PROCSTEP
     *
     * @param procstep the value for BATCHCLEARTRANS.PROCSTEP
     *
     * @mbggenerated
     */
    public void setProcstep(String procstep) {
        this.procstep = procstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PROCSTATUS
     *
     * @return the value of BATCHCLEARTRANS.PROCSTATUS
     *
     * @mbggenerated
     */
    public String getProcstatus() {
        return procstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PROCSTATUS
     *
     * @param procstatus the value for BATCHCLEARTRANS.PROCSTATUS
     *
     * @mbggenerated
     */
    public void setProcstatus(String procstatus) {
        this.procstatus = procstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MEMO1
     *
     * @return the value of BATCHCLEARTRANS.MEMO1
     *
     * @mbggenerated
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MEMO1
     *
     * @param memo1 the value for BATCHCLEARTRANS.MEMO1
     *
     * @mbggenerated
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSTIME
     *
     * @return the value of BATCHCLEARTRANS.TRANSTIME
     *
     * @mbggenerated
     */
    public Date getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSTIME
     *
     * @param transtime the value for BATCHCLEARTRANS.TRANSTIME
     *
     * @mbggenerated
     */
    public void setTranstime(Date transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.MEMO2
     *
     * @return the value of BATCHCLEARTRANS.MEMO2
     *
     * @mbggenerated
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.MEMO2
     *
     * @param memo2 the value for BATCHCLEARTRANS.MEMO2
     *
     * @mbggenerated
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DEPARTMENTNBR
     *
     * @return the value of BATCHCLEARTRANS.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public String getDepartmentnbr() {
        return departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DEPARTMENTNBR
     *
     * @param departmentnbr the value for BATCHCLEARTRANS.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public void setDepartmentnbr(String departmentnbr) {
        this.departmentnbr = departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DOWNSYSDATETIME
     *
     * @return the value of BATCHCLEARTRANS.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    public Date getDownsysdatetime() {
        return downsysdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DOWNSYSDATETIME
     *
     * @param downsysdatetime the value for BATCHCLEARTRANS.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    public void setDownsysdatetime(Date downsysdatetime) {
        this.downsysdatetime = downsysdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.SYSTEMCODE
     *
     * @return the value of BATCHCLEARTRANS.SYSTEMCODE
     *
     * @mbggenerated
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.SYSTEMCODE
     *
     * @param systemcode the value for BATCHCLEARTRANS.SYSTEMCODE
     *
     * @mbggenerated
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.TRANSMODE
     *
     * @return the value of BATCHCLEARTRANS.TRANSMODE
     *
     * @mbggenerated
     */
    public String getTransmode() {
        return transmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.TRANSMODE
     *
     * @param transmode the value for BATCHCLEARTRANS.TRANSMODE
     *
     * @mbggenerated
     */
    public void setTransmode(String transmode) {
        this.transmode = transmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.SIGNNBR
     *
     * @return the value of BATCHCLEARTRANS.SIGNNBR
     *
     * @mbggenerated
     */
    public String getSignnbr() {
        return signnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.SIGNNBR
     *
     * @param signnbr the value for BATCHCLEARTRANS.SIGNNBR
     *
     * @mbggenerated
     */
    public void setSignnbr(String signnbr) {
        this.signnbr = signnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PROFITSEQNBR
     *
     * @return the value of BATCHCLEARTRANS.PROFITSEQNBR
     *
     * @mbggenerated
     */
    public String getProfitseqnbr() {
        return profitseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PROFITSEQNBR
     *
     * @param profitseqnbr the value for BATCHCLEARTRANS.PROFITSEQNBR
     *
     * @mbggenerated
     */
    public void setProfitseqnbr(String profitseqnbr) {
        this.profitseqnbr = profitseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CONFIRMEDAMT
     *
     * @return the value of BATCHCLEARTRANS.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getConfirmedamt() {
        return confirmedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CONFIRMEDAMT
     *
     * @param confirmedamt the value for BATCHCLEARTRANS.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    public void setConfirmedamt(BigDecimal confirmedamt) {
        this.confirmedamt = confirmedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CONFIRMEDCOUNT
     *
     * @return the value of BATCHCLEARTRANS.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    public Long getConfirmedcount() {
        return confirmedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CONFIRMEDCOUNT
     *
     * @param confirmedcount the value for BATCHCLEARTRANS.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    public void setConfirmedcount(Long confirmedcount) {
        this.confirmedcount = confirmedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.REFUNDMODE
     *
     * @return the value of BATCHCLEARTRANS.REFUNDMODE
     *
     * @mbggenerated
     */
    public String getRefundmode() {
        return refundmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.REFUNDMODE
     *
     * @param refundmode the value for BATCHCLEARTRANS.REFUNDMODE
     *
     * @mbggenerated
     */
    public void setRefundmode(String refundmode) {
        this.refundmode = refundmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.INTERALAMT
     *
     * @return the value of BATCHCLEARTRANS.INTERALAMT
     *
     * @mbggenerated
     */
    public String getInteralamt() {
        return interalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.INTERALAMT
     *
     * @param interalamt the value for BATCHCLEARTRANS.INTERALAMT
     *
     * @mbggenerated
     */
    public void setInteralamt(String interalamt) {
        this.interalamt = interalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.INTERALFLAG
     *
     * @return the value of BATCHCLEARTRANS.INTERALFLAG
     *
     * @mbggenerated
     */
    public String getInteralflag() {
        return interalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.INTERALFLAG
     *
     * @param interalflag the value for BATCHCLEARTRANS.INTERALFLAG
     *
     * @mbggenerated
     */
    public void setInteralflag(String interalflag) {
        this.interalflag = interalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DEDUCTAMT
     *
     * @return the value of BATCHCLEARTRANS.DEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getDeductamt() {
        return deductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DEDUCTAMT
     *
     * @param deductamt the value for BATCHCLEARTRANS.DEDUCTAMT
     *
     * @mbggenerated
     */
    public void setDeductamt(BigDecimal deductamt) {
        this.deductamt = deductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.REALAMT
     *
     * @return the value of BATCHCLEARTRANS.REALAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRealamt() {
        return realamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.REALAMT
     *
     * @param realamt the value for BATCHCLEARTRANS.REALAMT
     *
     * @mbggenerated
     */
    public void setRealamt(BigDecimal realamt) {
        this.realamt = realamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.ORIGMERSEQNBR
     *
     * @return the value of BATCHCLEARTRANS.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    public String getOrigmerseqnbr() {
        return origmerseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.ORIGMERSEQNBR
     *
     * @param origmerseqnbr the value for BATCHCLEARTRANS.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    public void setOrigmerseqnbr(String origmerseqnbr) {
        this.origmerseqnbr = origmerseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.ORIGMERDATE
     *
     * @return the value of BATCHCLEARTRANS.ORIGMERDATE
     *
     * @mbggenerated
     */
    public Date getOrigmerdate() {
        return origmerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.ORIGMERDATE
     *
     * @param origmerdate the value for BATCHCLEARTRANS.ORIGMERDATE
     *
     * @mbggenerated
     */
    public void setOrigmerdate(Date origmerdate) {
        this.origmerdate = origmerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.ORIGSEQNBR
     *
     * @return the value of BATCHCLEARTRANS.ORIGSEQNBR
     *
     * @mbggenerated
     */
    public String getOrigseqnbr() {
        return origseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.ORIGSEQNBR
     *
     * @param origseqnbr the value for BATCHCLEARTRANS.ORIGSEQNBR
     *
     * @mbggenerated
     */
    public void setOrigseqnbr(String origseqnbr) {
        this.origseqnbr = origseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.ORIGCLEARDATE
     *
     * @return the value of BATCHCLEARTRANS.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    public Date getOrigcleardate() {
        return origcleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.ORIGCLEARDATE
     *
     * @param origcleardate the value for BATCHCLEARTRANS.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    public void setOrigcleardate(Date origcleardate) {
        this.origcleardate = origcleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CHECKSTATUS
     *
     * @return the value of BATCHCLEARTRANS.CHECKSTATUS
     *
     * @mbggenerated
     */
    public String getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CHECKSTATUS
     *
     * @param checkstatus the value for BATCHCLEARTRANS.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(String checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.PAYTYPCD
     *
     * @return the value of BATCHCLEARTRANS.PAYTYPCD
     *
     * @mbggenerated
     */
    public String getPaytypcd() {
        return paytypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.PAYTYPCD
     *
     * @param paytypcd the value for BATCHCLEARTRANS.PAYTYPCD
     *
     * @mbggenerated
     */
    public void setPaytypcd(String paytypcd) {
        this.paytypcd = paytypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CYBERTYPCD
     *
     * @return the value of BATCHCLEARTRANS.CYBERTYPCD
     *
     * @mbggenerated
     */
    public String getCybertypcd() {
        return cybertypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CYBERTYPCD
     *
     * @param cybertypcd the value for BATCHCLEARTRANS.CYBERTYPCD
     *
     * @mbggenerated
     */
    public void setCybertypcd(String cybertypcd) {
        this.cybertypcd = cybertypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DATELASTMAINT
     *
     * @return the value of BATCHCLEARTRANS.DATELASTMAINT
     *
     * @mbggenerated
     */
    public Date getDatelastmaint() {
        return datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DATELASTMAINT
     *
     * @param datelastmaint the value for BATCHCLEARTRANS.DATELASTMAINT
     *
     * @mbggenerated
     */
    protected void setDatelastmaint(Date datelastmaint) {
        this.datelastmaint = datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CLIENTNO
     *
     * @return the value of BATCHCLEARTRANS.CLIENTNO
     *
     * @mbggenerated
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CLIENTNO
     *
     * @param clientno the value for BATCHCLEARTRANS.CLIENTNO
     *
     * @mbggenerated
     */
    public void setClientno(String clientno) {
        this.clientno = clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.BRANCHNO
     *
     * @return the value of BATCHCLEARTRANS.BRANCHNO
     *
     * @mbggenerated
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.BRANCHNO
     *
     * @param branchno the value for BATCHCLEARTRANS.BRANCHNO
     *
     * @mbggenerated
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.POINTREACCTDEPTNBR
     *
     * @return the value of BATCHCLEARTRANS.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPointreacctdeptnbr() {
        return pointreacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.POINTREACCTDEPTNBR
     *
     * @param pointreacctdeptnbr the value for BATCHCLEARTRANS.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPointreacctdeptnbr(String pointreacctdeptnbr) {
        this.pointreacctdeptnbr = pointreacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.SUBPAYERACCTTYPE
     *
     * @return the value of BATCHCLEARTRANS.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    public String getSubpayeraccttype() {
        return subpayeraccttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.SUBPAYERACCTTYPE
     *
     * @param subpayeraccttype the value for BATCHCLEARTRANS.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    public void setSubpayeraccttype(String subpayeraccttype) {
        this.subpayeraccttype = subpayeraccttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.SUBPAYERACCTNBR
     *
     * @return the value of BATCHCLEARTRANS.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    public String getSubpayeracctnbr() {
        return subpayeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.SUBPAYERACCTNBR
     *
     * @param subpayeracctnbr the value for BATCHCLEARTRANS.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    public void setSubpayeracctnbr(String subpayeracctnbr) {
        this.subpayeracctnbr = subpayeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.UNREFUNDDEDUCTAMT
     *
     * @return the value of BATCHCLEARTRANS.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUnrefunddeductamt() {
        return unrefunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.UNREFUNDDEDUCTAMT
     *
     * @param unrefunddeductamt the value for BATCHCLEARTRANS.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public void setUnrefunddeductamt(BigDecimal unrefunddeductamt) {
        this.unrefunddeductamt = unrefunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.REFUNDDEDUCTAMT
     *
     * @return the value of BATCHCLEARTRANS.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRefunddeductamt() {
        return refunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.REFUNDDEDUCTAMT
     *
     * @param refunddeductamt the value for BATCHCLEARTRANS.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public void setRefunddeductamt(BigDecimal refunddeductamt) {
        this.refunddeductamt = refunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.RECEIPTAMT
     *
     * @return the value of BATCHCLEARTRANS.RECEIPTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getReceiptamt() {
        return receiptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.RECEIPTAMT
     *
     * @param receiptamt the value for BATCHCLEARTRANS.RECEIPTAMT
     *
     * @mbggenerated
     */
    public void setReceiptamt(BigDecimal receiptamt) {
        this.receiptamt = receiptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CODETYPCD
     *
     * @return the value of BATCHCLEARTRANS.CODETYPCD
     *
     * @mbggenerated
     */
    public String getCodetypcd() {
        return codetypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CODETYPCD
     *
     * @param codetypcd the value for BATCHCLEARTRANS.CODETYPCD
     *
     * @mbggenerated
     */
    public void setCodetypcd(String codetypcd) {
        this.codetypcd = codetypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.SCANCODEMODE
     *
     * @return the value of BATCHCLEARTRANS.SCANCODEMODE
     *
     * @mbggenerated
     */
    public String getScancodemode() {
        return scancodemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.SCANCODEMODE
     *
     * @param scancodemode the value for BATCHCLEARTRANS.SCANCODEMODE
     *
     * @mbggenerated
     */
    public void setScancodemode(String scancodemode) {
        this.scancodemode = scancodemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.QRCODEORDERNBR
     *
     * @return the value of BATCHCLEARTRANS.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    public String getQrcodeordernbr() {
        return qrcodeordernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.QRCODEORDERNBR
     *
     * @param qrcodeordernbr the value for BATCHCLEARTRANS.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    public void setQrcodeordernbr(String qrcodeordernbr) {
        this.qrcodeordernbr = qrcodeordernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.CODEURL
     *
     * @return the value of BATCHCLEARTRANS.CODEURL
     *
     * @mbggenerated
     */
    public String getCodeurl() {
        return codeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.CODEURL
     *
     * @param codeurl the value for BATCHCLEARTRANS.CODEURL
     *
     * @mbggenerated
     */
    public void setCodeurl(String codeurl) {
        this.codeurl = codeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.DISCOUNTABLEAMT
     *
     * @return the value of BATCHCLEARTRANS.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountableamt() {
        return discountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.DISCOUNTABLEAMT
     *
     * @param discountableamt the value for BATCHCLEARTRANS.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public void setDiscountableamt(BigDecimal discountableamt) {
        this.discountableamt = discountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCHCLEARTRANS.UNDISCOUNTABLEAMT
     *
     * @return the value of BATCHCLEARTRANS.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUndiscountableamt() {
        return undiscountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCHCLEARTRANS.UNDISCOUNTABLEAMT
     *
     * @param undiscountableamt the value for BATCHCLEARTRANS.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public void setUndiscountableamt(BigDecimal undiscountableamt) {
        this.undiscountableamt = undiscountableamt;
    }
}