package com.csii.upp.dto.generate;

import java.math.BigDecimal;
import java.util.Date;

public class Onlinetranshist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    private String transseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSDATE
     *
     * @mbggenerated
     */
    private Date transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MERSEQNBR
     *
     * @mbggenerated
     */
    private String merseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    private String downsystransnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CHANNELNBR
     *
     * @mbggenerated
     */
    private String channelnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CLEARDATE
     *
     * @mbggenerated
     */
    private Date cleardate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DOWNSYSDATE
     *
     * @mbggenerated
     */
    private Date downsysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MERTRANSDATE
     *
     * @mbggenerated
     */
    private Date mertransdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    private Date mertransdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSTYPCD
     *
     * @mbggenerated
     */
    private String transtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSCODE
     *
     * @mbggenerated
     */
    private String transcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MERNBR
     *
     * @mbggenerated
     */
    private String mernbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    private String meropendeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    private String merdevdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    private String custcifnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    private String payercardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    private String payeecardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    private String payeracctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeraccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    private String payeracctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeracctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    private String payeracctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    private String payeeacctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeeacctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    private String payeeacctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeeaccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    private String payeeacctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSAMT
     *
     * @mbggenerated
     */
    private BigDecimal transamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    private String currencycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.REFUNDEDAMT
     *
     * @mbggenerated
     */
    private BigDecimal refundedamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.UNREFUNDAMT
     *
     * @mbggenerated
     */
    private BigDecimal unrefundamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSAMT3
     *
     * @mbggenerated
     */
    private BigDecimal transamt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSAMT4
     *
     * @mbggenerated
     */
    private BigDecimal transamt4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.FEEAMT
     *
     * @mbggenerated
     */
    private BigDecimal feeamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    private String downsysrespcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.RESPCODE
     *
     * @mbggenerated
     */
    private String respcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    private String transstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PROCSTEP
     *
     * @mbggenerated
     */
    private String procstep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PROCSTATUS
     *
     * @mbggenerated
     */
    private String procstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MEMO1
     *
     * @mbggenerated
     */
    private String memo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSTIME
     *
     * @mbggenerated
     */
    private Date transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.MEMO2
     *
     * @mbggenerated
     */
    private String memo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    private String departmentnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    private Date downsysdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.SYSTEMCODE
     *
     * @mbggenerated
     */
    private String systemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.TRANSMODE
     *
     * @mbggenerated
     */
    private String transmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.SIGNNBR
     *
     * @mbggenerated
     */
    private String signnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PROFITSEQNBR
     *
     * @mbggenerated
     */
    private String profitseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    private BigDecimal confirmedamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    private Long confirmedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.REFUNDMODE
     *
     * @mbggenerated
     */
    private String refundmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.INTERALAMT
     *
     * @mbggenerated
     */
    private String interalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.INTERALFLAG
     *
     * @mbggenerated
     */
    private String interalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal deductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.REALAMT
     *
     * @mbggenerated
     */
    private BigDecimal realamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    private String origmerseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.ORIGMERDATE
     *
     * @mbggenerated
     */
    private Date origmerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.ORIGSEQNBR
     *
     * @mbggenerated
     */
    private String origseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    private Date origcleardate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CHECKSTATUS
     *
     * @mbggenerated
     */
    private String checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    private String paytypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CYBERTYPCD
     *
     * @mbggenerated
     */
    private String cybertypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    private Date datelastmaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CLIENTNO
     *
     * @mbggenerated
     */
    private String clientno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.BRANCHNO
     *
     * @mbggenerated
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String pointreacctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    private String subpayeraccttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    private String subpayeracctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal unrefunddeductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    private BigDecimal refunddeductamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.RECEIPTAMT
     *
     * @mbggenerated
     */
    private BigDecimal receiptamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CODETYPCD
     *
     * @mbggenerated
     */
    private String codetypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.SCANCODEMODE
     *
     * @mbggenerated
     */
    private String scancodemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    private String qrcodeordernbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.CODEURL
     *
     * @mbggenerated
     */
    private String codeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    private BigDecimal discountableamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINETRANSHIST.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    private BigDecimal undiscountableamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSSEQNBR
     *
     * @return the value of ONLINETRANSHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public String getTransseqnbr() {
        return transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSSEQNBR
     *
     * @param transseqnbr the value for ONLINETRANSHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public void setTransseqnbr(String transseqnbr) {
        this.transseqnbr = transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSDATE
     *
     * @return the value of ONLINETRANSHIST.TRANSDATE
     *
     * @mbggenerated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSDATE
     *
     * @param transdate the value for ONLINETRANSHIST.TRANSDATE
     *
     * @mbggenerated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MERSEQNBR
     *
     * @return the value of ONLINETRANSHIST.MERSEQNBR
     *
     * @mbggenerated
     */
    public String getMerseqnbr() {
        return merseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MERSEQNBR
     *
     * @param merseqnbr the value for ONLINETRANSHIST.MERSEQNBR
     *
     * @mbggenerated
     */
    public void setMerseqnbr(String merseqnbr) {
        this.merseqnbr = merseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DOWNSYSTRANSNBR
     *
     * @return the value of ONLINETRANSHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public String getDownsystransnbr() {
        return downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DOWNSYSTRANSNBR
     *
     * @param downsystransnbr the value for ONLINETRANSHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public void setDownsystransnbr(String downsystransnbr) {
        this.downsystransnbr = downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CHANNELNBR
     *
     * @return the value of ONLINETRANSHIST.CHANNELNBR
     *
     * @mbggenerated
     */
    public String getChannelnbr() {
        return channelnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CHANNELNBR
     *
     * @param channelnbr the value for ONLINETRANSHIST.CHANNELNBR
     *
     * @mbggenerated
     */
    public void setChannelnbr(String channelnbr) {
        this.channelnbr = channelnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CLEARDATE
     *
     * @return the value of ONLINETRANSHIST.CLEARDATE
     *
     * @mbggenerated
     */
    public Date getCleardate() {
        return cleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CLEARDATE
     *
     * @param cleardate the value for ONLINETRANSHIST.CLEARDATE
     *
     * @mbggenerated
     */
    public void setCleardate(Date cleardate) {
        this.cleardate = cleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DOWNSYSDATE
     *
     * @return the value of ONLINETRANSHIST.DOWNSYSDATE
     *
     * @mbggenerated
     */
    public Date getDownsysdate() {
        return downsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DOWNSYSDATE
     *
     * @param downsysdate the value for ONLINETRANSHIST.DOWNSYSDATE
     *
     * @mbggenerated
     */
    public void setDownsysdate(Date downsysdate) {
        this.downsysdate = downsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MERTRANSDATE
     *
     * @return the value of ONLINETRANSHIST.MERTRANSDATE
     *
     * @mbggenerated
     */
    public Date getMertransdate() {
        return mertransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MERTRANSDATE
     *
     * @param mertransdate the value for ONLINETRANSHIST.MERTRANSDATE
     *
     * @mbggenerated
     */
    public void setMertransdate(Date mertransdate) {
        this.mertransdate = mertransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MERTRANSDATETIME
     *
     * @return the value of ONLINETRANSHIST.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    public Date getMertransdatetime() {
        return mertransdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MERTRANSDATETIME
     *
     * @param mertransdatetime the value for ONLINETRANSHIST.MERTRANSDATETIME
     *
     * @mbggenerated
     */
    public void setMertransdatetime(Date mertransdatetime) {
        this.mertransdatetime = mertransdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSTYPCD
     *
     * @return the value of ONLINETRANSHIST.TRANSTYPCD
     *
     * @mbggenerated
     */
    public String getTranstypcd() {
        return transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSTYPCD
     *
     * @param transtypcd the value for ONLINETRANSHIST.TRANSTYPCD
     *
     * @mbggenerated
     */
    public void setTranstypcd(String transtypcd) {
        this.transtypcd = transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSCODE
     *
     * @return the value of ONLINETRANSHIST.TRANSCODE
     *
     * @mbggenerated
     */
    public String getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSCODE
     *
     * @param transcode the value for ONLINETRANSHIST.TRANSCODE
     *
     * @mbggenerated
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MERNBR
     *
     * @return the value of ONLINETRANSHIST.MERNBR
     *
     * @mbggenerated
     */
    public String getMernbr() {
        return mernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MERNBR
     *
     * @param mernbr the value for ONLINETRANSHIST.MERNBR
     *
     * @mbggenerated
     */
    public void setMernbr(String mernbr) {
        this.mernbr = mernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MEROPENDEPTNBR
     *
     * @return the value of ONLINETRANSHIST.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    public String getMeropendeptnbr() {
        return meropendeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MEROPENDEPTNBR
     *
     * @param meropendeptnbr the value for ONLINETRANSHIST.MEROPENDEPTNBR
     *
     * @mbggenerated
     */
    public void setMeropendeptnbr(String meropendeptnbr) {
        this.meropendeptnbr = meropendeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MERDEVDEPTNBR
     *
     * @return the value of ONLINETRANSHIST.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    public String getMerdevdeptnbr() {
        return merdevdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MERDEVDEPTNBR
     *
     * @param merdevdeptnbr the value for ONLINETRANSHIST.MERDEVDEPTNBR
     *
     * @mbggenerated
     */
    public void setMerdevdeptnbr(String merdevdeptnbr) {
        this.merdevdeptnbr = merdevdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CUSTCIFNBR
     *
     * @return the value of ONLINETRANSHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public String getCustcifnbr() {
        return custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CUSTCIFNBR
     *
     * @param custcifnbr the value for ONLINETRANSHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public void setCustcifnbr(String custcifnbr) {
        this.custcifnbr = custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERCARDTYPCD
     *
     * @return the value of ONLINETRANSHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayercardtypcd() {
        return payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERCARDTYPCD
     *
     * @param payercardtypcd the value for ONLINETRANSHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayercardtypcd(String payercardtypcd) {
        this.payercardtypcd = payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEECARDTYPCD
     *
     * @return the value of ONLINETRANSHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayeecardtypcd() {
        return payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEECARDTYPCD
     *
     * @param payeecardtypcd the value for ONLINETRANSHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayeecardtypcd(String payeecardtypcd) {
        this.payeecardtypcd = payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERACCTNBR
     *
     * @return the value of ONLINETRANSHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctnbr() {
        return payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERACCTNBR
     *
     * @param payeracctnbr the value for ONLINETRANSHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctnbr(String payeracctnbr) {
        this.payeracctnbr = payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERACCTTYPCD
     *
     * @return the value of ONLINETRANSHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeraccttypcd() {
        return payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERACCTTYPCD
     *
     * @param payeraccttypcd the value for ONLINETRANSHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeraccttypcd(String payeraccttypcd) {
        this.payeraccttypcd = payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERACCTKIND
     *
     * @return the value of ONLINETRANSHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeracctkind() {
        return payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERACCTKIND
     *
     * @param payeracctkind the value for ONLINETRANSHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeracctkind(String payeracctkind) {
        this.payeracctkind = payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERACCTDEPTNBR
     *
     * @return the value of ONLINETRANSHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctdeptnbr() {
        return payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERACCTDEPTNBR
     *
     * @param payeracctdeptnbr the value for ONLINETRANSHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctdeptnbr(String payeracctdeptnbr) {
        this.payeracctdeptnbr = payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYERACCTNAME
     *
     * @return the value of ONLINETRANSHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeracctname() {
        return payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYERACCTNAME
     *
     * @param payeracctname the value for ONLINETRANSHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeracctname(String payeracctname) {
        this.payeracctname = payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEEACCTNBR
     *
     * @return the value of ONLINETRANSHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctnbr() {
        return payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEEACCTNBR
     *
     * @param payeeacctnbr the value for ONLINETRANSHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctnbr(String payeeacctnbr) {
        this.payeeacctnbr = payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEEACCTDEPTNBR
     *
     * @return the value of ONLINETRANSHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctdeptnbr() {
        return payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEEACCTDEPTNBR
     *
     * @param payeeacctdeptnbr the value for ONLINETRANSHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctdeptnbr(String payeeacctdeptnbr) {
        this.payeeacctdeptnbr = payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEEACCTKIND
     *
     * @return the value of ONLINETRANSHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeeacctkind() {
        return payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEEACCTKIND
     *
     * @param payeeacctkind the value for ONLINETRANSHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeeacctkind(String payeeacctkind) {
        this.payeeacctkind = payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEEACCTTYPCD
     *
     * @return the value of ONLINETRANSHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeeaccttypcd() {
        return payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEEACCTTYPCD
     *
     * @param payeeaccttypcd the value for ONLINETRANSHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeeaccttypcd(String payeeaccttypcd) {
        this.payeeaccttypcd = payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYEEACCTNAME
     *
     * @return the value of ONLINETRANSHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeeacctname() {
        return payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYEEACCTNAME
     *
     * @param payeeacctname the value for ONLINETRANSHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeeacctname(String payeeacctname) {
        this.payeeacctname = payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSAMT
     *
     * @return the value of ONLINETRANSHIST.TRANSAMT
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt() {
        return transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSAMT
     *
     * @param transamt the value for ONLINETRANSHIST.TRANSAMT
     *
     * @mbggenerated
     */
    public void setTransamt(BigDecimal transamt) {
        this.transamt = transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CURRENCYCD
     *
     * @return the value of ONLINETRANSHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    public String getCurrencycd() {
        return currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CURRENCYCD
     *
     * @param currencycd the value for ONLINETRANSHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    public void setCurrencycd(String currencycd) {
        this.currencycd = currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.REFUNDEDAMT
     *
     * @return the value of ONLINETRANSHIST.REFUNDEDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRefundedamt() {
        return refundedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.REFUNDEDAMT
     *
     * @param refundedamt the value for ONLINETRANSHIST.REFUNDEDAMT
     *
     * @mbggenerated
     */
    public void setRefundedamt(BigDecimal refundedamt) {
        this.refundedamt = refundedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.UNREFUNDAMT
     *
     * @return the value of ONLINETRANSHIST.UNREFUNDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUnrefundamt() {
        return unrefundamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.UNREFUNDAMT
     *
     * @param unrefundamt the value for ONLINETRANSHIST.UNREFUNDAMT
     *
     * @mbggenerated
     */
    public void setUnrefundamt(BigDecimal unrefundamt) {
        this.unrefundamt = unrefundamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSAMT3
     *
     * @return the value of ONLINETRANSHIST.TRANSAMT3
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt3() {
        return transamt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSAMT3
     *
     * @param transamt3 the value for ONLINETRANSHIST.TRANSAMT3
     *
     * @mbggenerated
     */
    public void setTransamt3(BigDecimal transamt3) {
        this.transamt3 = transamt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSAMT4
     *
     * @return the value of ONLINETRANSHIST.TRANSAMT4
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt4() {
        return transamt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSAMT4
     *
     * @param transamt4 the value for ONLINETRANSHIST.TRANSAMT4
     *
     * @mbggenerated
     */
    public void setTransamt4(BigDecimal transamt4) {
        this.transamt4 = transamt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.FEEAMT
     *
     * @return the value of ONLINETRANSHIST.FEEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getFeeamt() {
        return feeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.FEEAMT
     *
     * @param feeamt the value for ONLINETRANSHIST.FEEAMT
     *
     * @mbggenerated
     */
    public void setFeeamt(BigDecimal feeamt) {
        this.feeamt = feeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DOWNSYSRESPCODE
     *
     * @return the value of ONLINETRANSHIST.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    public String getDownsysrespcode() {
        return downsysrespcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DOWNSYSRESPCODE
     *
     * @param downsysrespcode the value for ONLINETRANSHIST.DOWNSYSRESPCODE
     *
     * @mbggenerated
     */
    public void setDownsysrespcode(String downsysrespcode) {
        this.downsysrespcode = downsysrespcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.RESPCODE
     *
     * @return the value of ONLINETRANSHIST.RESPCODE
     *
     * @mbggenerated
     */
    public String getRespcode() {
        return respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.RESPCODE
     *
     * @param respcode the value for ONLINETRANSHIST.RESPCODE
     *
     * @mbggenerated
     */
    public void setRespcode(String respcode) {
        this.respcode = respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSSTATUS
     *
     * @return the value of ONLINETRANSHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    public String getTransstatus() {
        return transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSSTATUS
     *
     * @param transstatus the value for ONLINETRANSHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    public void setTransstatus(String transstatus) {
        this.transstatus = transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PROCSTEP
     *
     * @return the value of ONLINETRANSHIST.PROCSTEP
     *
     * @mbggenerated
     */
    public String getProcstep() {
        return procstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PROCSTEP
     *
     * @param procstep the value for ONLINETRANSHIST.PROCSTEP
     *
     * @mbggenerated
     */
    public void setProcstep(String procstep) {
        this.procstep = procstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PROCSTATUS
     *
     * @return the value of ONLINETRANSHIST.PROCSTATUS
     *
     * @mbggenerated
     */
    public String getProcstatus() {
        return procstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PROCSTATUS
     *
     * @param procstatus the value for ONLINETRANSHIST.PROCSTATUS
     *
     * @mbggenerated
     */
    public void setProcstatus(String procstatus) {
        this.procstatus = procstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MEMO1
     *
     * @return the value of ONLINETRANSHIST.MEMO1
     *
     * @mbggenerated
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MEMO1
     *
     * @param memo1 the value for ONLINETRANSHIST.MEMO1
     *
     * @mbggenerated
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSTIME
     *
     * @return the value of ONLINETRANSHIST.TRANSTIME
     *
     * @mbggenerated
     */
    public Date getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSTIME
     *
     * @param transtime the value for ONLINETRANSHIST.TRANSTIME
     *
     * @mbggenerated
     */
    public void setTranstime(Date transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.MEMO2
     *
     * @return the value of ONLINETRANSHIST.MEMO2
     *
     * @mbggenerated
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.MEMO2
     *
     * @param memo2 the value for ONLINETRANSHIST.MEMO2
     *
     * @mbggenerated
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DEPARTMENTNBR
     *
     * @return the value of ONLINETRANSHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public String getDepartmentnbr() {
        return departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DEPARTMENTNBR
     *
     * @param departmentnbr the value for ONLINETRANSHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public void setDepartmentnbr(String departmentnbr) {
        this.departmentnbr = departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DOWNSYSDATETIME
     *
     * @return the value of ONLINETRANSHIST.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    public Date getDownsysdatetime() {
        return downsysdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DOWNSYSDATETIME
     *
     * @param downsysdatetime the value for ONLINETRANSHIST.DOWNSYSDATETIME
     *
     * @mbggenerated
     */
    public void setDownsysdatetime(Date downsysdatetime) {
        this.downsysdatetime = downsysdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.SYSTEMCODE
     *
     * @return the value of ONLINETRANSHIST.SYSTEMCODE
     *
     * @mbggenerated
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.SYSTEMCODE
     *
     * @param systemcode the value for ONLINETRANSHIST.SYSTEMCODE
     *
     * @mbggenerated
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.TRANSMODE
     *
     * @return the value of ONLINETRANSHIST.TRANSMODE
     *
     * @mbggenerated
     */
    public String getTransmode() {
        return transmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.TRANSMODE
     *
     * @param transmode the value for ONLINETRANSHIST.TRANSMODE
     *
     * @mbggenerated
     */
    public void setTransmode(String transmode) {
        this.transmode = transmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.SIGNNBR
     *
     * @return the value of ONLINETRANSHIST.SIGNNBR
     *
     * @mbggenerated
     */
    public String getSignnbr() {
        return signnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.SIGNNBR
     *
     * @param signnbr the value for ONLINETRANSHIST.SIGNNBR
     *
     * @mbggenerated
     */
    public void setSignnbr(String signnbr) {
        this.signnbr = signnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PROFITSEQNBR
     *
     * @return the value of ONLINETRANSHIST.PROFITSEQNBR
     *
     * @mbggenerated
     */
    public String getProfitseqnbr() {
        return profitseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PROFITSEQNBR
     *
     * @param profitseqnbr the value for ONLINETRANSHIST.PROFITSEQNBR
     *
     * @mbggenerated
     */
    public void setProfitseqnbr(String profitseqnbr) {
        this.profitseqnbr = profitseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CONFIRMEDAMT
     *
     * @return the value of ONLINETRANSHIST.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    public BigDecimal getConfirmedamt() {
        return confirmedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CONFIRMEDAMT
     *
     * @param confirmedamt the value for ONLINETRANSHIST.CONFIRMEDAMT
     *
     * @mbggenerated
     */
    public void setConfirmedamt(BigDecimal confirmedamt) {
        this.confirmedamt = confirmedamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CONFIRMEDCOUNT
     *
     * @return the value of ONLINETRANSHIST.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    public Long getConfirmedcount() {
        return confirmedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CONFIRMEDCOUNT
     *
     * @param confirmedcount the value for ONLINETRANSHIST.CONFIRMEDCOUNT
     *
     * @mbggenerated
     */
    public void setConfirmedcount(Long confirmedcount) {
        this.confirmedcount = confirmedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.REFUNDMODE
     *
     * @return the value of ONLINETRANSHIST.REFUNDMODE
     *
     * @mbggenerated
     */
    public String getRefundmode() {
        return refundmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.REFUNDMODE
     *
     * @param refundmode the value for ONLINETRANSHIST.REFUNDMODE
     *
     * @mbggenerated
     */
    public void setRefundmode(String refundmode) {
        this.refundmode = refundmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.INTERALAMT
     *
     * @return the value of ONLINETRANSHIST.INTERALAMT
     *
     * @mbggenerated
     */
    public String getInteralamt() {
        return interalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.INTERALAMT
     *
     * @param interalamt the value for ONLINETRANSHIST.INTERALAMT
     *
     * @mbggenerated
     */
    public void setInteralamt(String interalamt) {
        this.interalamt = interalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.INTERALFLAG
     *
     * @return the value of ONLINETRANSHIST.INTERALFLAG
     *
     * @mbggenerated
     */
    public String getInteralflag() {
        return interalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.INTERALFLAG
     *
     * @param interalflag the value for ONLINETRANSHIST.INTERALFLAG
     *
     * @mbggenerated
     */
    public void setInteralflag(String interalflag) {
        this.interalflag = interalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DEDUCTAMT
     *
     * @return the value of ONLINETRANSHIST.DEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getDeductamt() {
        return deductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DEDUCTAMT
     *
     * @param deductamt the value for ONLINETRANSHIST.DEDUCTAMT
     *
     * @mbggenerated
     */
    public void setDeductamt(BigDecimal deductamt) {
        this.deductamt = deductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.REALAMT
     *
     * @return the value of ONLINETRANSHIST.REALAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRealamt() {
        return realamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.REALAMT
     *
     * @param realamt the value for ONLINETRANSHIST.REALAMT
     *
     * @mbggenerated
     */
    public void setRealamt(BigDecimal realamt) {
        this.realamt = realamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.ORIGMERSEQNBR
     *
     * @return the value of ONLINETRANSHIST.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    public String getOrigmerseqnbr() {
        return origmerseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.ORIGMERSEQNBR
     *
     * @param origmerseqnbr the value for ONLINETRANSHIST.ORIGMERSEQNBR
     *
     * @mbggenerated
     */
    public void setOrigmerseqnbr(String origmerseqnbr) {
        this.origmerseqnbr = origmerseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.ORIGMERDATE
     *
     * @return the value of ONLINETRANSHIST.ORIGMERDATE
     *
     * @mbggenerated
     */
    public Date getOrigmerdate() {
        return origmerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.ORIGMERDATE
     *
     * @param origmerdate the value for ONLINETRANSHIST.ORIGMERDATE
     *
     * @mbggenerated
     */
    public void setOrigmerdate(Date origmerdate) {
        this.origmerdate = origmerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.ORIGSEQNBR
     *
     * @return the value of ONLINETRANSHIST.ORIGSEQNBR
     *
     * @mbggenerated
     */
    public String getOrigseqnbr() {
        return origseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.ORIGSEQNBR
     *
     * @param origseqnbr the value for ONLINETRANSHIST.ORIGSEQNBR
     *
     * @mbggenerated
     */
    public void setOrigseqnbr(String origseqnbr) {
        this.origseqnbr = origseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.ORIGCLEARDATE
     *
     * @return the value of ONLINETRANSHIST.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    public Date getOrigcleardate() {
        return origcleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.ORIGCLEARDATE
     *
     * @param origcleardate the value for ONLINETRANSHIST.ORIGCLEARDATE
     *
     * @mbggenerated
     */
    public void setOrigcleardate(Date origcleardate) {
        this.origcleardate = origcleardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CHECKSTATUS
     *
     * @return the value of ONLINETRANSHIST.CHECKSTATUS
     *
     * @mbggenerated
     */
    public String getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CHECKSTATUS
     *
     * @param checkstatus the value for ONLINETRANSHIST.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(String checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.PAYTYPCD
     *
     * @return the value of ONLINETRANSHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    public String getPaytypcd() {
        return paytypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.PAYTYPCD
     *
     * @param paytypcd the value for ONLINETRANSHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    public void setPaytypcd(String paytypcd) {
        this.paytypcd = paytypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CYBERTYPCD
     *
     * @return the value of ONLINETRANSHIST.CYBERTYPCD
     *
     * @mbggenerated
     */
    public String getCybertypcd() {
        return cybertypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CYBERTYPCD
     *
     * @param cybertypcd the value for ONLINETRANSHIST.CYBERTYPCD
     *
     * @mbggenerated
     */
    public void setCybertypcd(String cybertypcd) {
        this.cybertypcd = cybertypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DATELASTMAINT
     *
     * @return the value of ONLINETRANSHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    public Date getDatelastmaint() {
        return datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DATELASTMAINT
     *
     * @param datelastmaint the value for ONLINETRANSHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    protected void setDatelastmaint(Date datelastmaint) {
        this.datelastmaint = datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CLIENTNO
     *
     * @return the value of ONLINETRANSHIST.CLIENTNO
     *
     * @mbggenerated
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CLIENTNO
     *
     * @param clientno the value for ONLINETRANSHIST.CLIENTNO
     *
     * @mbggenerated
     */
    public void setClientno(String clientno) {
        this.clientno = clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.BRANCHNO
     *
     * @return the value of ONLINETRANSHIST.BRANCHNO
     *
     * @mbggenerated
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.BRANCHNO
     *
     * @param branchno the value for ONLINETRANSHIST.BRANCHNO
     *
     * @mbggenerated
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.POINTREACCTDEPTNBR
     *
     * @return the value of ONLINETRANSHIST.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPointreacctdeptnbr() {
        return pointreacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.POINTREACCTDEPTNBR
     *
     * @param pointreacctdeptnbr the value for ONLINETRANSHIST.POINTREACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPointreacctdeptnbr(String pointreacctdeptnbr) {
        this.pointreacctdeptnbr = pointreacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.SUBPAYERACCTTYPE
     *
     * @return the value of ONLINETRANSHIST.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    public String getSubpayeraccttype() {
        return subpayeraccttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.SUBPAYERACCTTYPE
     *
     * @param subpayeraccttype the value for ONLINETRANSHIST.SUBPAYERACCTTYPE
     *
     * @mbggenerated
     */
    public void setSubpayeraccttype(String subpayeraccttype) {
        this.subpayeraccttype = subpayeraccttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.SUBPAYERACCTNBR
     *
     * @return the value of ONLINETRANSHIST.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    public String getSubpayeracctnbr() {
        return subpayeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.SUBPAYERACCTNBR
     *
     * @param subpayeracctnbr the value for ONLINETRANSHIST.SUBPAYERACCTNBR
     *
     * @mbggenerated
     */
    public void setSubpayeracctnbr(String subpayeracctnbr) {
        this.subpayeracctnbr = subpayeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.UNREFUNDDEDUCTAMT
     *
     * @return the value of ONLINETRANSHIST.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUnrefunddeductamt() {
        return unrefunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.UNREFUNDDEDUCTAMT
     *
     * @param unrefunddeductamt the value for ONLINETRANSHIST.UNREFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public void setUnrefunddeductamt(BigDecimal unrefunddeductamt) {
        this.unrefunddeductamt = unrefunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.REFUNDDEDUCTAMT
     *
     * @return the value of ONLINETRANSHIST.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getRefunddeductamt() {
        return refunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.REFUNDDEDUCTAMT
     *
     * @param refunddeductamt the value for ONLINETRANSHIST.REFUNDDEDUCTAMT
     *
     * @mbggenerated
     */
    public void setRefunddeductamt(BigDecimal refunddeductamt) {
        this.refunddeductamt = refunddeductamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.RECEIPTAMT
     *
     * @return the value of ONLINETRANSHIST.RECEIPTAMT
     *
     * @mbggenerated
     */
    public BigDecimal getReceiptamt() {
        return receiptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.RECEIPTAMT
     *
     * @param receiptamt the value for ONLINETRANSHIST.RECEIPTAMT
     *
     * @mbggenerated
     */
    public void setReceiptamt(BigDecimal receiptamt) {
        this.receiptamt = receiptamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CODETYPCD
     *
     * @return the value of ONLINETRANSHIST.CODETYPCD
     *
     * @mbggenerated
     */
    public String getCodetypcd() {
        return codetypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CODETYPCD
     *
     * @param codetypcd the value for ONLINETRANSHIST.CODETYPCD
     *
     * @mbggenerated
     */
    public void setCodetypcd(String codetypcd) {
        this.codetypcd = codetypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.SCANCODEMODE
     *
     * @return the value of ONLINETRANSHIST.SCANCODEMODE
     *
     * @mbggenerated
     */
    public String getScancodemode() {
        return scancodemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.SCANCODEMODE
     *
     * @param scancodemode the value for ONLINETRANSHIST.SCANCODEMODE
     *
     * @mbggenerated
     */
    public void setScancodemode(String scancodemode) {
        this.scancodemode = scancodemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.QRCODEORDERNBR
     *
     * @return the value of ONLINETRANSHIST.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    public String getQrcodeordernbr() {
        return qrcodeordernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.QRCODEORDERNBR
     *
     * @param qrcodeordernbr the value for ONLINETRANSHIST.QRCODEORDERNBR
     *
     * @mbggenerated
     */
    public void setQrcodeordernbr(String qrcodeordernbr) {
        this.qrcodeordernbr = qrcodeordernbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.CODEURL
     *
     * @return the value of ONLINETRANSHIST.CODEURL
     *
     * @mbggenerated
     */
    public String getCodeurl() {
        return codeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.CODEURL
     *
     * @param codeurl the value for ONLINETRANSHIST.CODEURL
     *
     * @mbggenerated
     */
    public void setCodeurl(String codeurl) {
        this.codeurl = codeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.DISCOUNTABLEAMT
     *
     * @return the value of ONLINETRANSHIST.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountableamt() {
        return discountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.DISCOUNTABLEAMT
     *
     * @param discountableamt the value for ONLINETRANSHIST.DISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public void setDiscountableamt(BigDecimal discountableamt) {
        this.discountableamt = discountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINETRANSHIST.UNDISCOUNTABLEAMT
     *
     * @return the value of ONLINETRANSHIST.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public BigDecimal getUndiscountableamt() {
        return undiscountableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINETRANSHIST.UNDISCOUNTABLEAMT
     *
     * @param undiscountableamt the value for ONLINETRANSHIST.UNDISCOUNTABLEAMT
     *
     * @mbggenerated
     */
    public void setUndiscountableamt(BigDecimal undiscountableamt) {
        this.undiscountableamt = undiscountableamt;
    }
}