package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Innerfundtranshistall;
import com.csii.upp.dto.generate.InnerfundtranshistallExample;

public class InnerfundtranshistallDAO extends BasePayDAO {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int countByExample(InnerfundtranshistallExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("INNERFUNDTRANSHISTALL.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int deleteByExample(InnerfundtranshistallExample example) throws SQLException {
        int rows = getSqlMap().delete("INNERFUNDTRANSHISTALL.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String innerfundtransnbr) throws SQLException {
        Innerfundtranshistall _key = new Innerfundtranshistall();
        _key.setInnerfundtransnbr(innerfundtransnbr);
        int rows = getSqlMap().delete("INNERFUNDTRANSHISTALL.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static void insert(Innerfundtranshistall record) throws SQLException {
        getSqlMap().insert("INNERFUNDTRANSHISTALL.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static void insertSelective(Innerfundtranshistall record) throws SQLException {
        getSqlMap().insert("INNERFUNDTRANSHISTALL.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Innerfundtranshistall> selectByExample(InnerfundtranshistallExample example) throws SQLException {
        List<Innerfundtranshistall> list = getSqlMap().queryForList("INNERFUNDTRANSHISTALL.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static Innerfundtranshistall selectByPrimaryKey(String innerfundtransnbr) throws SQLException {
        Innerfundtranshistall _key = new Innerfundtranshistall();
        _key.setInnerfundtransnbr(innerfundtransnbr);
        Innerfundtranshistall record = (Innerfundtranshistall) getSqlMap().queryForObject("INNERFUNDTRANSHISTALL.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Innerfundtranshistall record, InnerfundtranshistallExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("INNERFUNDTRANSHISTALL.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByExample(Innerfundtranshistall record, InnerfundtranshistallExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("INNERFUNDTRANSHISTALL.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Innerfundtranshistall record) throws SQLException {
        int rows = getSqlMap().update("INNERFUNDTRANSHISTALL.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Innerfundtranshistall record) throws SQLException {
        int rows = getSqlMap().update("INNERFUNDTRANSHISTALL.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNERFUNDTRANSHISTALL
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends InnerfundtranshistallExample {
        private Object record;

        public UpdateByExampleParms(Object record, InnerfundtranshistallExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}