package com.csii.upp.dto.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ParameterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public ParameterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected ParameterExample(ParameterExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.distinct = example.distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PARAMETER
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected GeneratedCriteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andParametercdIsNull() {
			addCriterion("PARAMETERCD is null");
			return (Criteria) this;
		}

		public Criteria andParametercdIsNotNull() {
			addCriterion("PARAMETERCD is not null");
			return (Criteria) this;
		}

		public Criteria andParametercdEqualTo(String value) {
			addCriterion("PARAMETERCD =", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdNotEqualTo(String value) {
			addCriterion("PARAMETERCD <>", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdGreaterThan(String value) {
			addCriterion("PARAMETERCD >", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdGreaterThanOrEqualTo(String value) {
			addCriterion("PARAMETERCD >=", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdLessThan(String value) {
			addCriterion("PARAMETERCD <", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdLessThanOrEqualTo(String value) {
			addCriterion("PARAMETERCD <=", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdLike(String value) {
			addCriterion("PARAMETERCD like", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdNotLike(String value) {
			addCriterion("PARAMETERCD not like", value, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdIn(List<String> values) {
			addCriterion("PARAMETERCD in", values, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdNotIn(List<String> values) {
			addCriterion("PARAMETERCD not in", values, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdBetween(String value1, String value2) {
			addCriterion("PARAMETERCD between", value1, value2, "parametercd");
			return (Criteria) this;
		}

		public Criteria andParametercdNotBetween(String value1, String value2) {
			addCriterion("PARAMETERCD not between", value1, value2,
					"parametercd");
			return (Criteria) this;
		}

		public Criteria andParameterdescIsNull() {
			addCriterion("PARAMETERDESC is null");
			return (Criteria) this;
		}

		public Criteria andParameterdescIsNotNull() {
			addCriterion("PARAMETERDESC is not null");
			return (Criteria) this;
		}

		public Criteria andParameterdescEqualTo(String value) {
			addCriterion("PARAMETERDESC =", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescNotEqualTo(String value) {
			addCriterion("PARAMETERDESC <>", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescGreaterThan(String value) {
			addCriterion("PARAMETERDESC >", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescGreaterThanOrEqualTo(String value) {
			addCriterion("PARAMETERDESC >=", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescLessThan(String value) {
			addCriterion("PARAMETERDESC <", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescLessThanOrEqualTo(String value) {
			addCriterion("PARAMETERDESC <=", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescLike(String value) {
			addCriterion("PARAMETERDESC like", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescNotLike(String value) {
			addCriterion("PARAMETERDESC not like", value, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescIn(List<String> values) {
			addCriterion("PARAMETERDESC in", values, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescNotIn(List<String> values) {
			addCriterion("PARAMETERDESC not in", values, "parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescBetween(String value1, String value2) {
			addCriterion("PARAMETERDESC between", value1, value2,
					"parameterdesc");
			return (Criteria) this;
		}

		public Criteria andParameterdescNotBetween(String value1, String value2) {
			addCriterion("PARAMETERDESC not between", value1, value2,
					"parameterdesc");
			return (Criteria) this;
		}

		public Criteria andDatatypcdIsNull() {
			addCriterion("DATATYPCD is null");
			return (Criteria) this;
		}

		public Criteria andDatatypcdIsNotNull() {
			addCriterion("DATATYPCD is not null");
			return (Criteria) this;
		}

		public Criteria andDatatypcdEqualTo(String value) {
			addCriterion("DATATYPCD =", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdNotEqualTo(String value) {
			addCriterion("DATATYPCD <>", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdGreaterThan(String value) {
			addCriterion("DATATYPCD >", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdGreaterThanOrEqualTo(String value) {
			addCriterion("DATATYPCD >=", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdLessThan(String value) {
			addCriterion("DATATYPCD <", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdLessThanOrEqualTo(String value) {
			addCriterion("DATATYPCD <=", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdLike(String value) {
			addCriterion("DATATYPCD like", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdNotLike(String value) {
			addCriterion("DATATYPCD not like", value, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdIn(List<String> values) {
			addCriterion("DATATYPCD in", values, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdNotIn(List<String> values) {
			addCriterion("DATATYPCD not in", values, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdBetween(String value1, String value2) {
			addCriterion("DATATYPCD between", value1, value2, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatatypcdNotBetween(String value1, String value2) {
			addCriterion("DATATYPCD not between", value1, value2, "datatypcd");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintIsNull() {
			addCriterion("DATELASTMAINT is null");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintIsNotNull() {
			addCriterion("DATELASTMAINT is not null");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintEqualTo(Date value) {
			addCriterion("DATELASTMAINT =", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintNotEqualTo(Date value) {
			addCriterion("DATELASTMAINT <>", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintGreaterThan(Date value) {
			addCriterion("DATELASTMAINT >", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintGreaterThanOrEqualTo(Date value) {
			addCriterion("DATELASTMAINT >=", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintLessThan(Date value) {
			addCriterion("DATELASTMAINT <", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintLessThanOrEqualTo(Date value) {
			addCriterion("DATELASTMAINT <=", value, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintIn(List<Date> values) {
			addCriterion("DATELASTMAINT in", values, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintNotIn(List<Date> values) {
			addCriterion("DATELASTMAINT not in", values, "datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintBetween(Date value1, Date value2) {
			addCriterion("DATELASTMAINT between", value1, value2,
					"datelastmaint");
			return (Criteria) this;
		}

		public Criteria andDatelastmaintNotBetween(Date value1, Date value2) {
			addCriterion("DATELASTMAINT not between", value1, value2,
					"datelastmaint");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARAMETER
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}