package com.csii.upp.dto.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class SysinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public SysinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected SysinfoExample(SysinfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSINFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFundchannelcodeIsNull() {
            addCriterion("FUNDCHANNELCODE is null");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeIsNotNull() {
            addCriterion("FUNDCHANNELCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeEqualTo(String value) {
            addCriterion("FUNDCHANNELCODE =", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeNotEqualTo(String value) {
            addCriterion("FUNDCHANNELCODE <>", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeGreaterThan(String value) {
            addCriterion("FUNDCHANNELCODE >", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDCHANNELCODE >=", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeLessThan(String value) {
            addCriterion("FUNDCHANNELCODE <", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeLessThanOrEqualTo(String value) {
            addCriterion("FUNDCHANNELCODE <=", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeLike(String value) {
            addCriterion("FUNDCHANNELCODE like", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeNotLike(String value) {
            addCriterion("FUNDCHANNELCODE not like", value, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeIn(List<String> values) {
            addCriterion("FUNDCHANNELCODE in", values, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeNotIn(List<String> values) {
            addCriterion("FUNDCHANNELCODE not in", values, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeBetween(String value1, String value2) {
            addCriterion("FUNDCHANNELCODE between", value1, value2, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andFundchannelcodeNotBetween(String value1, String value2) {
            addCriterion("FUNDCHANNELCODE not between", value1, value2, "fundchannelcode");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateIsNull() {
            addCriterion("PREVPOSTDATE is null");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateIsNotNull() {
            addCriterion("PREVPOSTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateEqualTo(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE =", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE <>", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateGreaterThan(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE >", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE >=", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateLessThan(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE <", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PREVPOSTDATE <=", value, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateIn(List<Date> values) {
            addCriterionForJDBCDate("PREVPOSTDATE in", values, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PREVPOSTDATE not in", values, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PREVPOSTDATE between", value1, value2, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPrevpostdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PREVPOSTDATE not between", value1, value2, "prevpostdate");
            return (Criteria) this;
        }

        public Criteria andPostdateIsNull() {
            addCriterion("POSTDATE is null");
            return (Criteria) this;
        }

        public Criteria andPostdateIsNotNull() {
            addCriterion("POSTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPostdateEqualTo(Date value) {
            addCriterionForJDBCDate("POSTDATE =", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("POSTDATE <>", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateGreaterThan(Date value) {
            addCriterionForJDBCDate("POSTDATE >", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("POSTDATE >=", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateLessThan(Date value) {
            addCriterionForJDBCDate("POSTDATE <", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("POSTDATE <=", value, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateIn(List<Date> values) {
            addCriterionForJDBCDate("POSTDATE in", values, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("POSTDATE not in", values, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("POSTDATE between", value1, value2, "postdate");
            return (Criteria) this;
        }

        public Criteria andPostdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("POSTDATE not between", value1, value2, "postdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateIsNull() {
            addCriterion("NEXTPOSTDATE is null");
            return (Criteria) this;
        }

        public Criteria andNextpostdateIsNotNull() {
            addCriterion("NEXTPOSTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andNextpostdateEqualTo(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE =", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE <>", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateGreaterThan(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE >", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE >=", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateLessThan(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE <", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NEXTPOSTDATE <=", value, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateIn(List<Date> values) {
            addCriterionForJDBCDate("NEXTPOSTDATE in", values, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("NEXTPOSTDATE not in", values, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NEXTPOSTDATE between", value1, value2, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andNextpostdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NEXTPOSTDATE not between", value1, value2, "nextpostdate");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andClearresultIsNull() {
            addCriterion("CLEARRESULT is null");
            return (Criteria) this;
        }

        public Criteria andClearresultIsNotNull() {
            addCriterion("CLEARRESULT is not null");
            return (Criteria) this;
        }

        public Criteria andClearresultEqualTo(String value) {
            addCriterion("CLEARRESULT =", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultNotEqualTo(String value) {
            addCriterion("CLEARRESULT <>", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultGreaterThan(String value) {
            addCriterion("CLEARRESULT >", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultGreaterThanOrEqualTo(String value) {
            addCriterion("CLEARRESULT >=", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultLessThan(String value) {
            addCriterion("CLEARRESULT <", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultLessThanOrEqualTo(String value) {
            addCriterion("CLEARRESULT <=", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultLike(String value) {
            addCriterion("CLEARRESULT like", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultNotLike(String value) {
            addCriterion("CLEARRESULT not like", value, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultIn(List<String> values) {
            addCriterion("CLEARRESULT in", values, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultNotIn(List<String> values) {
            addCriterion("CLEARRESULT not in", values, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultBetween(String value1, String value2) {
            addCriterion("CLEARRESULT between", value1, value2, "clearresult");
            return (Criteria) this;
        }

        public Criteria andClearresultNotBetween(String value1, String value2) {
            addCriterion("CLEARRESULT not between", value1, value2, "clearresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultIsNull() {
            addCriterion("CHECKRESULT is null");
            return (Criteria) this;
        }

        public Criteria andCheckresultIsNotNull() {
            addCriterion("CHECKRESULT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckresultEqualTo(String value) {
            addCriterion("CHECKRESULT =", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultNotEqualTo(String value) {
            addCriterion("CHECKRESULT <>", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultGreaterThan(String value) {
            addCriterion("CHECKRESULT >", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKRESULT >=", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultLessThan(String value) {
            addCriterion("CHECKRESULT <", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultLessThanOrEqualTo(String value) {
            addCriterion("CHECKRESULT <=", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultLike(String value) {
            addCriterion("CHECKRESULT like", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultNotLike(String value) {
            addCriterion("CHECKRESULT not like", value, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultIn(List<String> values) {
            addCriterion("CHECKRESULT in", values, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultNotIn(List<String> values) {
            addCriterion("CHECKRESULT not in", values, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultBetween(String value1, String value2) {
            addCriterion("CHECKRESULT between", value1, value2, "checkresult");
            return (Criteria) this;
        }

        public Criteria andCheckresultNotBetween(String value1, String value2) {
            addCriterion("CHECKRESULT not between", value1, value2, "checkresult");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusIsNull() {
            addCriterion("DOWNSYSSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusIsNotNull() {
            addCriterion("DOWNSYSSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusEqualTo(String value) {
            addCriterion("DOWNSYSSTATUS =", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusNotEqualTo(String value) {
            addCriterion("DOWNSYSSTATUS <>", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusGreaterThan(String value) {
            addCriterion("DOWNSYSSTATUS >", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusGreaterThanOrEqualTo(String value) {
            addCriterion("DOWNSYSSTATUS >=", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusLessThan(String value) {
            addCriterion("DOWNSYSSTATUS <", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusLessThanOrEqualTo(String value) {
            addCriterion("DOWNSYSSTATUS <=", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusLike(String value) {
            addCriterion("DOWNSYSSTATUS like", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusNotLike(String value) {
            addCriterion("DOWNSYSSTATUS not like", value, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusIn(List<String> values) {
            addCriterion("DOWNSYSSTATUS in", values, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusNotIn(List<String> values) {
            addCriterion("DOWNSYSSTATUS not in", values, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusBetween(String value1, String value2) {
            addCriterion("DOWNSYSSTATUS between", value1, value2, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andDownsysstatusNotBetween(String value1, String value2) {
            addCriterion("DOWNSYSSTATUS not between", value1, value2, "downsysstatus");
            return (Criteria) this;
        }

        public Criteria andMemo1IsNull() {
            addCriterion("MEMO1 is null");
            return (Criteria) this;
        }

        public Criteria andMemo1IsNotNull() {
            addCriterion("MEMO1 is not null");
            return (Criteria) this;
        }

        public Criteria andMemo1EqualTo(String value) {
            addCriterion("MEMO1 =", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1NotEqualTo(String value) {
            addCriterion("MEMO1 <>", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1GreaterThan(String value) {
            addCriterion("MEMO1 >", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1GreaterThanOrEqualTo(String value) {
            addCriterion("MEMO1 >=", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1LessThan(String value) {
            addCriterion("MEMO1 <", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1LessThanOrEqualTo(String value) {
            addCriterion("MEMO1 <=", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1Like(String value) {
            addCriterion("MEMO1 like", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1NotLike(String value) {
            addCriterion("MEMO1 not like", value, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1In(List<String> values) {
            addCriterion("MEMO1 in", values, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1NotIn(List<String> values) {
            addCriterion("MEMO1 not in", values, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1Between(String value1, String value2) {
            addCriterion("MEMO1 between", value1, value2, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo1NotBetween(String value1, String value2) {
            addCriterion("MEMO1 not between", value1, value2, "memo1");
            return (Criteria) this;
        }

        public Criteria andMemo2IsNull() {
            addCriterion("MEMO2 is null");
            return (Criteria) this;
        }

        public Criteria andMemo2IsNotNull() {
            addCriterion("MEMO2 is not null");
            return (Criteria) this;
        }

        public Criteria andMemo2EqualTo(String value) {
            addCriterion("MEMO2 =", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2NotEqualTo(String value) {
            addCriterion("MEMO2 <>", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2GreaterThan(String value) {
            addCriterion("MEMO2 >", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2GreaterThanOrEqualTo(String value) {
            addCriterion("MEMO2 >=", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2LessThan(String value) {
            addCriterion("MEMO2 <", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2LessThanOrEqualTo(String value) {
            addCriterion("MEMO2 <=", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2Like(String value) {
            addCriterion("MEMO2 like", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2NotLike(String value) {
            addCriterion("MEMO2 not like", value, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2In(List<String> values) {
            addCriterion("MEMO2 in", values, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2NotIn(List<String> values) {
            addCriterion("MEMO2 not in", values, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2Between(String value1, String value2) {
            addCriterion("MEMO2 between", value1, value2, "memo2");
            return (Criteria) this;
        }

        public Criteria andMemo2NotBetween(String value1, String value2) {
            addCriterion("MEMO2 not between", value1, value2, "memo2");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNull() {
            addCriterion("DATELASTMAINT is null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNotNull() {
            addCriterion("DATELASTMAINT is not null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintEqualTo(Date value) {
            addCriterion("DATELASTMAINT =", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotEqualTo(Date value) {
            addCriterion("DATELASTMAINT <>", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThan(Date value) {
            addCriterion("DATELASTMAINT >", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT >=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThan(Date value) {
            addCriterion("DATELASTMAINT <", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT <=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIn(List<Date> values) {
            addCriterion("DATELASTMAINT in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotIn(List<Date> values) {
            addCriterion("DATELASTMAINT not in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT not between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andSysstateIsNull() {
            addCriterion("SYSSTATE is null");
            return (Criteria) this;
        }

        public Criteria andSysstateIsNotNull() {
            addCriterion("SYSSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andSysstateEqualTo(String value) {
            addCriterion("SYSSTATE =", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateNotEqualTo(String value) {
            addCriterion("SYSSTATE <>", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateGreaterThan(String value) {
            addCriterion("SYSSTATE >", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateGreaterThanOrEqualTo(String value) {
            addCriterion("SYSSTATE >=", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateLessThan(String value) {
            addCriterion("SYSSTATE <", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateLessThanOrEqualTo(String value) {
            addCriterion("SYSSTATE <=", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateLike(String value) {
            addCriterion("SYSSTATE like", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateNotLike(String value) {
            addCriterion("SYSSTATE not like", value, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateIn(List<String> values) {
            addCriterion("SYSSTATE in", values, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateNotIn(List<String> values) {
            addCriterion("SYSSTATE not in", values, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateBetween(String value1, String value2) {
            addCriterion("SYSSTATE between", value1, value2, "sysstate");
            return (Criteria) this;
        }

        public Criteria andSysstateNotBetween(String value1, String value2) {
            addCriterion("SYSSTATE not between", value1, value2, "sysstate");
            return (Criteria) this;
        }

        public Criteria andHolidayflagIsNull() {
            addCriterion("HOLIDAYFLAG is null");
            return (Criteria) this;
        }

        public Criteria andHolidayflagIsNotNull() {
            addCriterion("HOLIDAYFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayflagEqualTo(String value) {
            addCriterion("HOLIDAYFLAG =", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagNotEqualTo(String value) {
            addCriterion("HOLIDAYFLAG <>", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagGreaterThan(String value) {
            addCriterion("HOLIDAYFLAG >", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagGreaterThanOrEqualTo(String value) {
            addCriterion("HOLIDAYFLAG >=", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagLessThan(String value) {
            addCriterion("HOLIDAYFLAG <", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagLessThanOrEqualTo(String value) {
            addCriterion("HOLIDAYFLAG <=", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagLike(String value) {
            addCriterion("HOLIDAYFLAG like", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagNotLike(String value) {
            addCriterion("HOLIDAYFLAG not like", value, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagIn(List<String> values) {
            addCriterion("HOLIDAYFLAG in", values, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagNotIn(List<String> values) {
            addCriterion("HOLIDAYFLAG not in", values, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagBetween(String value1, String value2) {
            addCriterion("HOLIDAYFLAG between", value1, value2, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andHolidayflagNotBetween(String value1, String value2) {
            addCriterion("HOLIDAYFLAG not between", value1, value2, "holidayflag");
            return (Criteria) this;
        }

        public Criteria andPreworkroundIsNull() {
            addCriterion("PREWORKROUND is null");
            return (Criteria) this;
        }

        public Criteria andPreworkroundIsNotNull() {
            addCriterion("PREWORKROUND is not null");
            return (Criteria) this;
        }

        public Criteria andPreworkroundEqualTo(Long value) {
            addCriterion("PREWORKROUND =", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundNotEqualTo(Long value) {
            addCriterion("PREWORKROUND <>", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundGreaterThan(Long value) {
            addCriterion("PREWORKROUND >", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundGreaterThanOrEqualTo(Long value) {
            addCriterion("PREWORKROUND >=", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundLessThan(Long value) {
            addCriterion("PREWORKROUND <", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundLessThanOrEqualTo(Long value) {
            addCriterion("PREWORKROUND <=", value, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundIn(List<Long> values) {
            addCriterion("PREWORKROUND in", values, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundNotIn(List<Long> values) {
            addCriterion("PREWORKROUND not in", values, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundBetween(Long value1, Long value2) {
            addCriterion("PREWORKROUND between", value1, value2, "preworkround");
            return (Criteria) this;
        }

        public Criteria andPreworkroundNotBetween(Long value1, Long value2) {
            addCriterion("PREWORKROUND not between", value1, value2, "preworkround");
            return (Criteria) this;
        }

        public Criteria andWorkgroupIsNull() {
            addCriterion("WORKGROUP is null");
            return (Criteria) this;
        }

        public Criteria andWorkgroupIsNotNull() {
            addCriterion("WORKGROUP is not null");
            return (Criteria) this;
        }

        public Criteria andWorkgroupEqualTo(Long value) {
            addCriterion("WORKGROUP =", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupNotEqualTo(Long value) {
            addCriterion("WORKGROUP <>", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupGreaterThan(Long value) {
            addCriterion("WORKGROUP >", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupGreaterThanOrEqualTo(Long value) {
            addCriterion("WORKGROUP >=", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupLessThan(Long value) {
            addCriterion("WORKGROUP <", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupLessThanOrEqualTo(Long value) {
            addCriterion("WORKGROUP <=", value, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupIn(List<Long> values) {
            addCriterion("WORKGROUP in", values, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupNotIn(List<Long> values) {
            addCriterion("WORKGROUP not in", values, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupBetween(Long value1, Long value2) {
            addCriterion("WORKGROUP between", value1, value2, "workgroup");
            return (Criteria) this;
        }

        public Criteria andWorkgroupNotBetween(Long value1, Long value2) {
            addCriterion("WORKGROUP not between", value1, value2, "workgroup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSINFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}