package com.csii.upp.dto.generate;

import java.math.BigDecimal;
import java.util.Date;

public class Feeparam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.FEENBR
     *
     * @mbggenerated
     */
    private String feenbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.TRANSTYPCD
     *
     * @mbggenerated
     */
    private String transtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.FLOATFLAG
     *
     * @mbggenerated
     */
    private String floatflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.DEDUCTFLAG
     *
     * @mbggenerated
     */
    private String deductflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.BOUNDFLAG
     *
     * @mbggenerated
     */
    private String boundflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.UPPERLIMITVAL
     *
     * @mbggenerated
     */
    private BigDecimal upperlimitval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.LOWERLIMITVAL
     *
     * @mbggenerated
     */
    private BigDecimal lowerlimitval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.CALCULATETYP
     *
     * @mbggenerated
     */
    private String calculatetyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.CALCULATEPARAM
     *
     * @mbggenerated
     */
    private String calculateparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.FLOATTYP
     *
     * @mbggenerated
     */
    private String floattyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.PROGRESSFLAG
     *
     * @mbggenerated
     */
    private String progressflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.CONTAINFLAG
     *
     * @mbggenerated
     */
    private String containflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.STARTPARAM
     *
     * @mbggenerated
     */
    private String startparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.ENDPARAM
     *
     * @mbggenerated
     */
    private String endparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.DATELASTMAINT
     *
     * @mbggenerated
     */
    private Date datelastmaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FEEPARAM.SEQNBR
     *
     * @mbggenerated
     */
    private String seqnbr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.FEENBR
     *
     * @return the value of FEEPARAM.FEENBR
     *
     * @mbggenerated
     */
    public String getFeenbr() {
        return feenbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.FEENBR
     *
     * @param feenbr the value for FEEPARAM.FEENBR
     *
     * @mbggenerated
     */
    public void setFeenbr(String feenbr) {
        this.feenbr = feenbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.TRANSTYPCD
     *
     * @return the value of FEEPARAM.TRANSTYPCD
     *
     * @mbggenerated
     */
    public String getTranstypcd() {
        return transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.TRANSTYPCD
     *
     * @param transtypcd the value for FEEPARAM.TRANSTYPCD
     *
     * @mbggenerated
     */
    public void setTranstypcd(String transtypcd) {
        this.transtypcd = transtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.FLOATFLAG
     *
     * @return the value of FEEPARAM.FLOATFLAG
     *
     * @mbggenerated
     */
    public String getFloatflag() {
        return floatflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.FLOATFLAG
     *
     * @param floatflag the value for FEEPARAM.FLOATFLAG
     *
     * @mbggenerated
     */
    public void setFloatflag(String floatflag) {
        this.floatflag = floatflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.DEDUCTFLAG
     *
     * @return the value of FEEPARAM.DEDUCTFLAG
     *
     * @mbggenerated
     */
    public String getDeductflag() {
        return deductflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.DEDUCTFLAG
     *
     * @param deductflag the value for FEEPARAM.DEDUCTFLAG
     *
     * @mbggenerated
     */
    public void setDeductflag(String deductflag) {
        this.deductflag = deductflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.BOUNDFLAG
     *
     * @return the value of FEEPARAM.BOUNDFLAG
     *
     * @mbggenerated
     */
    public String getBoundflag() {
        return boundflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.BOUNDFLAG
     *
     * @param boundflag the value for FEEPARAM.BOUNDFLAG
     *
     * @mbggenerated
     */
    public void setBoundflag(String boundflag) {
        this.boundflag = boundflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.UPPERLIMITVAL
     *
     * @return the value of FEEPARAM.UPPERLIMITVAL
     *
     * @mbggenerated
     */
    public BigDecimal getUpperlimitval() {
        return upperlimitval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.UPPERLIMITVAL
     *
     * @param upperlimitval the value for FEEPARAM.UPPERLIMITVAL
     *
     * @mbggenerated
     */
    public void setUpperlimitval(BigDecimal upperlimitval) {
        this.upperlimitval = upperlimitval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.LOWERLIMITVAL
     *
     * @return the value of FEEPARAM.LOWERLIMITVAL
     *
     * @mbggenerated
     */
    public BigDecimal getLowerlimitval() {
        return lowerlimitval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.LOWERLIMITVAL
     *
     * @param lowerlimitval the value for FEEPARAM.LOWERLIMITVAL
     *
     * @mbggenerated
     */
    public void setLowerlimitval(BigDecimal lowerlimitval) {
        this.lowerlimitval = lowerlimitval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.CALCULATETYP
     *
     * @return the value of FEEPARAM.CALCULATETYP
     *
     * @mbggenerated
     */
    public String getCalculatetyp() {
        return calculatetyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.CALCULATETYP
     *
     * @param calculatetyp the value for FEEPARAM.CALCULATETYP
     *
     * @mbggenerated
     */
    public void setCalculatetyp(String calculatetyp) {
        this.calculatetyp = calculatetyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.CALCULATEPARAM
     *
     * @return the value of FEEPARAM.CALCULATEPARAM
     *
     * @mbggenerated
     */
    public String getCalculateparam() {
        return calculateparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.CALCULATEPARAM
     *
     * @param calculateparam the value for FEEPARAM.CALCULATEPARAM
     *
     * @mbggenerated
     */
    public void setCalculateparam(String calculateparam) {
        this.calculateparam = calculateparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.FLOATTYP
     *
     * @return the value of FEEPARAM.FLOATTYP
     *
     * @mbggenerated
     */
    public String getFloattyp() {
        return floattyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.FLOATTYP
     *
     * @param floattyp the value for FEEPARAM.FLOATTYP
     *
     * @mbggenerated
     */
    public void setFloattyp(String floattyp) {
        this.floattyp = floattyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.PROGRESSFLAG
     *
     * @return the value of FEEPARAM.PROGRESSFLAG
     *
     * @mbggenerated
     */
    public String getProgressflag() {
        return progressflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.PROGRESSFLAG
     *
     * @param progressflag the value for FEEPARAM.PROGRESSFLAG
     *
     * @mbggenerated
     */
    public void setProgressflag(String progressflag) {
        this.progressflag = progressflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.CONTAINFLAG
     *
     * @return the value of FEEPARAM.CONTAINFLAG
     *
     * @mbggenerated
     */
    public String getContainflag() {
        return containflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.CONTAINFLAG
     *
     * @param containflag the value for FEEPARAM.CONTAINFLAG
     *
     * @mbggenerated
     */
    public void setContainflag(String containflag) {
        this.containflag = containflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.STARTPARAM
     *
     * @return the value of FEEPARAM.STARTPARAM
     *
     * @mbggenerated
     */
    public String getStartparam() {
        return startparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.STARTPARAM
     *
     * @param startparam the value for FEEPARAM.STARTPARAM
     *
     * @mbggenerated
     */
    public void setStartparam(String startparam) {
        this.startparam = startparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.ENDPARAM
     *
     * @return the value of FEEPARAM.ENDPARAM
     *
     * @mbggenerated
     */
    public String getEndparam() {
        return endparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.ENDPARAM
     *
     * @param endparam the value for FEEPARAM.ENDPARAM
     *
     * @mbggenerated
     */
    public void setEndparam(String endparam) {
        this.endparam = endparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.MEMO
     *
     * @return the value of FEEPARAM.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.MEMO
     *
     * @param memo the value for FEEPARAM.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.DATELASTMAINT
     *
     * @return the value of FEEPARAM.DATELASTMAINT
     *
     * @mbggenerated
     */
    public Date getDatelastmaint() {
        return datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.DATELASTMAINT
     *
     * @param datelastmaint the value for FEEPARAM.DATELASTMAINT
     *
     * @mbggenerated
     */
    protected void setDatelastmaint(Date datelastmaint) {
        this.datelastmaint = datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FEEPARAM.SEQNBR
     *
     * @return the value of FEEPARAM.SEQNBR
     *
     * @mbggenerated
     */
    public String getSeqnbr() {
        return seqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FEEPARAM.SEQNBR
     *
     * @param seqnbr the value for FEEPARAM.SEQNBR
     *
     * @mbggenerated
     */
    public void setSeqnbr(String seqnbr) {
        this.seqnbr = seqnbr;
    }
}