package com.csii.upp.dto.generate;

import java.util.Date;

public class Queapplparam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.QUENBR
	 * @mbggenerated
	 */
	private Long quenbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.QUESUBNBR
	 * @mbggenerated
	 */
	private Long quesubnbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.APPLNBR
	 * @mbggenerated
	 */
	private Long applnbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.PARAMETERCD
	 * @mbggenerated
	 */
	private String parametercd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.PARAMETERVALUE
	 * @mbggenerated
	 */
	private String parametervalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.DATELASTMAINT
	 * @mbggenerated
	 */
	private Date datelastmaint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.DISPLAYSEQNBR
	 * @mbggenerated
	 */
	private Long displayseqnbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.SEQNBR
	 * @mbggenerated
	 */
	private Long seqnbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUEAPPLPARAM.VALUECHANGEYN
	 * @mbggenerated
	 */
	private String valuechangeyn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.QUENBR
	 * @return  the value of QUEAPPLPARAM.QUENBR
	 * @mbggenerated
	 */
	public Long getQuenbr() {
		return quenbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.QUENBR
	 * @param quenbr  the value for QUEAPPLPARAM.QUENBR
	 * @mbggenerated
	 */
	public void setQuenbr(Long quenbr) {
		this.quenbr = quenbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.QUESUBNBR
	 * @return  the value of QUEAPPLPARAM.QUESUBNBR
	 * @mbggenerated
	 */
	public Long getQuesubnbr() {
		return quesubnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.QUESUBNBR
	 * @param quesubnbr  the value for QUEAPPLPARAM.QUESUBNBR
	 * @mbggenerated
	 */
	public void setQuesubnbr(Long quesubnbr) {
		this.quesubnbr = quesubnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.APPLNBR
	 * @return  the value of QUEAPPLPARAM.APPLNBR
	 * @mbggenerated
	 */
	public Long getApplnbr() {
		return applnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.APPLNBR
	 * @param applnbr  the value for QUEAPPLPARAM.APPLNBR
	 * @mbggenerated
	 */
	public void setApplnbr(Long applnbr) {
		this.applnbr = applnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.PARAMETERCD
	 * @return  the value of QUEAPPLPARAM.PARAMETERCD
	 * @mbggenerated
	 */
	public String getParametercd() {
		return parametercd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.PARAMETERCD
	 * @param parametercd  the value for QUEAPPLPARAM.PARAMETERCD
	 * @mbggenerated
	 */
	public void setParametercd(String parametercd) {
		this.parametercd = parametercd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.PARAMETERVALUE
	 * @return  the value of QUEAPPLPARAM.PARAMETERVALUE
	 * @mbggenerated
	 */
	public String getParametervalue() {
		return parametervalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.PARAMETERVALUE
	 * @param parametervalue  the value for QUEAPPLPARAM.PARAMETERVALUE
	 * @mbggenerated
	 */
	public void setParametervalue(String parametervalue) {
		this.parametervalue = parametervalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.DATELASTMAINT
	 * @return  the value of QUEAPPLPARAM.DATELASTMAINT
	 * @mbggenerated
	 */
	public Date getDatelastmaint() {
		return datelastmaint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.DATELASTMAINT
	 * @param datelastmaint  the value for QUEAPPLPARAM.DATELASTMAINT
	 * @mbggenerated
	 */
	protected void setDatelastmaint(Date datelastmaint) {
		this.datelastmaint = datelastmaint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.DISPLAYSEQNBR
	 * @return  the value of QUEAPPLPARAM.DISPLAYSEQNBR
	 * @mbggenerated
	 */
	public Long getDisplayseqnbr() {
		return displayseqnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.DISPLAYSEQNBR
	 * @param displayseqnbr  the value for QUEAPPLPARAM.DISPLAYSEQNBR
	 * @mbggenerated
	 */
	public void setDisplayseqnbr(Long displayseqnbr) {
		this.displayseqnbr = displayseqnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.SEQNBR
	 * @return  the value of QUEAPPLPARAM.SEQNBR
	 * @mbggenerated
	 */
	public Long getSeqnbr() {
		return seqnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.SEQNBR
	 * @param seqnbr  the value for QUEAPPLPARAM.SEQNBR
	 * @mbggenerated
	 */
	public void setSeqnbr(Long seqnbr) {
		this.seqnbr = seqnbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUEAPPLPARAM.VALUECHANGEYN
	 * @return  the value of QUEAPPLPARAM.VALUECHANGEYN
	 * @mbggenerated
	 */
	public String getValuechangeyn() {
		return valuechangeyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUEAPPLPARAM.VALUECHANGEYN
	 * @param valuechangeyn  the value for QUEAPPLPARAM.VALUECHANGEYN
	 * @mbggenerated
	 */
	public void setValuechangeyn(String valuechangeyn) {
		this.valuechangeyn = valuechangeyn;
	}
}