package com.csii.upp.qrcodeplatform.generate.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QrcodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public QrcodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQrcodenbrIsNull() {
            addCriterion("QRCODENBR is null");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrIsNotNull() {
            addCriterion("QRCODENBR is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrEqualTo(String value) {
            addCriterion("QRCODENBR =", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrNotEqualTo(String value) {
            addCriterion("QRCODENBR <>", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrGreaterThan(String value) {
            addCriterion("QRCODENBR >", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrGreaterThanOrEqualTo(String value) {
            addCriterion("QRCODENBR >=", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrLessThan(String value) {
            addCriterion("QRCODENBR <", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrLessThanOrEqualTo(String value) {
            addCriterion("QRCODENBR <=", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrLike(String value) {
            addCriterion("QRCODENBR like", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrNotLike(String value) {
            addCriterion("QRCODENBR not like", value, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrIn(List<String> values) {
            addCriterion("QRCODENBR in", values, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrNotIn(List<String> values) {
            addCriterion("QRCODENBR not in", values, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrBetween(String value1, String value2) {
            addCriterion("QRCODENBR between", value1, value2, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodenbrNotBetween(String value1, String value2) {
            addCriterion("QRCODENBR not between", value1, value2, "qrcodenbr");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeIsNull() {
            addCriterion("QRCODETYPE is null");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeIsNotNull() {
            addCriterion("QRCODETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeEqualTo(String value) {
            addCriterion("QRCODETYPE =", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeNotEqualTo(String value) {
            addCriterion("QRCODETYPE <>", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeGreaterThan(String value) {
            addCriterion("QRCODETYPE >", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeGreaterThanOrEqualTo(String value) {
            addCriterion("QRCODETYPE >=", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeLessThan(String value) {
            addCriterion("QRCODETYPE <", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeLessThanOrEqualTo(String value) {
            addCriterion("QRCODETYPE <=", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeLike(String value) {
            addCriterion("QRCODETYPE like", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeNotLike(String value) {
            addCriterion("QRCODETYPE not like", value, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeIn(List<String> values) {
            addCriterion("QRCODETYPE in", values, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeNotIn(List<String> values) {
            addCriterion("QRCODETYPE not in", values, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeBetween(String value1, String value2) {
            addCriterion("QRCODETYPE between", value1, value2, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andQrcodetypeNotBetween(String value1, String value2) {
            addCriterion("QRCODETYPE not between", value1, value2, "qrcodetype");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrIsNull() {
            addCriterion("SENDTDEPTNBR is null");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrIsNotNull() {
            addCriterion("SENDTDEPTNBR is not null");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrEqualTo(String value) {
            addCriterion("SENDTDEPTNBR =", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrNotEqualTo(String value) {
            addCriterion("SENDTDEPTNBR <>", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrGreaterThan(String value) {
            addCriterion("SENDTDEPTNBR >", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrGreaterThanOrEqualTo(String value) {
            addCriterion("SENDTDEPTNBR >=", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrLessThan(String value) {
            addCriterion("SENDTDEPTNBR <", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrLessThanOrEqualTo(String value) {
            addCriterion("SENDTDEPTNBR <=", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrLike(String value) {
            addCriterion("SENDTDEPTNBR like", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrNotLike(String value) {
            addCriterion("SENDTDEPTNBR not like", value, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrIn(List<String> values) {
            addCriterion("SENDTDEPTNBR in", values, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrNotIn(List<String> values) {
            addCriterion("SENDTDEPTNBR not in", values, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrBetween(String value1, String value2) {
            addCriterion("SENDTDEPTNBR between", value1, value2, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andSendtdeptnbrNotBetween(String value1, String value2) {
            addCriterion("SENDTDEPTNBR not between", value1, value2, "sendtdeptnbr");
            return (Criteria) this;
        }

        public Criteria andValidityminuteIsNull() {
            addCriterion("VALIDITYMINUTE is null");
            return (Criteria) this;
        }

        public Criteria andValidityminuteIsNotNull() {
            addCriterion("VALIDITYMINUTE is not null");
            return (Criteria) this;
        }

        public Criteria andValidityminuteEqualTo(String value) {
            addCriterion("VALIDITYMINUTE =", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteNotEqualTo(String value) {
            addCriterion("VALIDITYMINUTE <>", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteGreaterThan(String value) {
            addCriterion("VALIDITYMINUTE >", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDITYMINUTE >=", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteLessThan(String value) {
            addCriterion("VALIDITYMINUTE <", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteLessThanOrEqualTo(String value) {
            addCriterion("VALIDITYMINUTE <=", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteLike(String value) {
            addCriterion("VALIDITYMINUTE like", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteNotLike(String value) {
            addCriterion("VALIDITYMINUTE not like", value, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteIn(List<String> values) {
            addCriterion("VALIDITYMINUTE in", values, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteNotIn(List<String> values) {
            addCriterion("VALIDITYMINUTE not in", values, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteBetween(String value1, String value2) {
            addCriterion("VALIDITYMINUTE between", value1, value2, "validityminute");
            return (Criteria) this;
        }

        public Criteria andValidityminuteNotBetween(String value1, String value2) {
            addCriterion("VALIDITYMINUTE not between", value1, value2, "validityminute");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampIsNull() {
            addCriterion("UPDATETIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampIsNotNull() {
            addCriterion("UPDATETIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampEqualTo(Date value) {
            addCriterion("UPDATETIMESTAMP =", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampNotEqualTo(Date value) {
            addCriterion("UPDATETIMESTAMP <>", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampGreaterThan(Date value) {
            addCriterion("UPDATETIMESTAMP >", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIMESTAMP >=", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampLessThan(Date value) {
            addCriterion("UPDATETIMESTAMP <", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIMESTAMP <=", value, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampIn(List<Date> values) {
            addCriterion("UPDATETIMESTAMP in", values, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampNotIn(List<Date> values) {
            addCriterion("UPDATETIMESTAMP not in", values, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATETIMESTAMP between", value1, value2, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdatetimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIMESTAMP not between", value1, value2, "updatetimestamp");
            return (Criteria) this;
        }

        public Criteria andVerificationcountIsNull() {
            addCriterion("VERIFICATIONCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andVerificationcountIsNotNull() {
            addCriterion("VERIFICATIONCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andVerificationcountEqualTo(String value) {
            addCriterion("VERIFICATIONCOUNT =", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountNotEqualTo(String value) {
            addCriterion("VERIFICATIONCOUNT <>", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountGreaterThan(String value) {
            addCriterion("VERIFICATIONCOUNT >", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFICATIONCOUNT >=", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountLessThan(String value) {
            addCriterion("VERIFICATIONCOUNT <", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountLessThanOrEqualTo(String value) {
            addCriterion("VERIFICATIONCOUNT <=", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountLike(String value) {
            addCriterion("VERIFICATIONCOUNT like", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountNotLike(String value) {
            addCriterion("VERIFICATIONCOUNT not like", value, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountIn(List<String> values) {
            addCriterion("VERIFICATIONCOUNT in", values, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountNotIn(List<String> values) {
            addCriterion("VERIFICATIONCOUNT not in", values, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountBetween(String value1, String value2) {
            addCriterion("VERIFICATIONCOUNT between", value1, value2, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andVerificationcountNotBetween(String value1, String value2) {
            addCriterion("VERIFICATIONCOUNT not between", value1, value2, "verificationcount");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNull() {
            addCriterion("DATELASTMAINT is null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNotNull() {
            addCriterion("DATELASTMAINT is not null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintEqualTo(Date value) {
            addCriterion("DATELASTMAINT =", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotEqualTo(Date value) {
            addCriterion("DATELASTMAINT <>", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThan(Date value) {
            addCriterion("DATELASTMAINT >", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT >=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThan(Date value) {
            addCriterion("DATELASTMAINT <", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT <=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIn(List<Date> values) {
            addCriterion("DATELASTMAINT in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotIn(List<Date> values) {
            addCriterion("DATELASTMAINT not in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT not between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qrcode
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qrcode
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}