package com.csii.upp.qrcodeplatform.generate.dao;

import com.csii.upp.qrcodeplatform.generate.dao.model.Upperchannel;
import com.csii.upp.qrcodeplatform.generate.dao.model.UpperchannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpperchannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int countByExample(UpperchannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int deleteByExample(UpperchannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int deleteByPrimaryKey(String channelnbr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int insert(Upperchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int insertSelective(Upperchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    List<Upperchannel> selectByExample(UpperchannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    Upperchannel selectByPrimaryKey(String channelnbr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") Upperchannel record, @Param("example") UpperchannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int updateByExample(@Param("record") Upperchannel record, @Param("example") UpperchannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int updateByPrimaryKeySelective(Upperchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    int updateByPrimaryKey(Upperchannel record);
}