package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Agency;
import com.csii.upp.dto.generate.AgencyExample;

public class AgencyDAO extends BasePayDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int countByExample(AgencyExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("AGENCY.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int deleteByExample(AgencyExample example) throws SQLException {
        int rows = getSqlMap().delete("AGENCY.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String agencynbr) throws SQLException {
        Agency _key = new Agency();
        _key.setAgencynbr(agencynbr);
        int rows = getSqlMap().delete("AGENCY.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public void insert(Agency record) throws SQLException {
        getSqlMap().insert("AGENCY.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static void insertSelective(Agency record) throws SQLException {
        getSqlMap().insert("AGENCY.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Agency> selectByExample(AgencyExample example) throws SQLException {
        List<Agency> list = getSqlMap().queryForList("AGENCY.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static Agency selectByPrimaryKey(String agencynbr) throws SQLException {
        Agency _key = new Agency();
        _key.setAgencynbr(agencynbr);
        Agency record = (Agency) getSqlMap().queryForObject("AGENCY.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Agency record, AgencyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("AGENCY.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int updateByExample(Agency record, AgencyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("AGENCY.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Agency record) throws SQLException {
        int rows = getSqlMap().update("AGENCY.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Agency record) throws SQLException {
        int rows = getSqlMap().update("AGENCY.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENCY
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends AgencyExample {
        private Object record;

        public UpdateByExampleParms(Object record, AgencyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}