package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Bankoptioncat;
import com.csii.upp.dto.generate.BankoptioncatExample;

public class BankoptioncatDAO extends BasePayDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int countByExample(BankoptioncatExample example) throws SQLException {
		Integer count = (Integer) getSqlMap().queryForObject(
				"BANKOPTIONCAT.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int deleteByExample(BankoptioncatExample example)
			throws SQLException {
		int rows = getSqlMap().delete("BANKOPTIONCAT.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int deleteByPrimaryKey(String bankoptioncatcd) throws SQLException {
		Bankoptioncat _key = new Bankoptioncat();
		_key.setBankoptioncatcd(bankoptioncatcd);
		int rows = getSqlMap().delete("BANKOPTIONCAT.deleteByPrimaryKey", _key);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static void insert(Bankoptioncat record) throws SQLException {
		getSqlMap().insert("BANKOPTIONCAT.insert", record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static void insertSelective(Bankoptioncat record) throws SQLException {
		getSqlMap().insert("BANKOPTIONCAT.insertSelective", record);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	@SuppressWarnings("unchecked")
	public static List<Bankoptioncat> selectByExample(BankoptioncatExample example)
			throws SQLException {
		List<Bankoptioncat> list = getSqlMap().queryForList(
				"BANKOPTIONCAT.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static Bankoptioncat selectByPrimaryKey(String bankoptioncatcd)
			throws SQLException {
		Bankoptioncat _key = new Bankoptioncat();
		_key.setBankoptioncatcd(bankoptioncatcd);
		Bankoptioncat record = (Bankoptioncat) getSqlMap().queryForObject(
				"BANKOPTIONCAT.selectByPrimaryKey", _key);
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int updateByExampleSelective(Bankoptioncat record,
			BankoptioncatExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMap().update(
				"BANKOPTIONCAT.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int updateByExample(Bankoptioncat record,
			BankoptioncatExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMap().update("BANKOPTIONCAT.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int updateByPrimaryKeySelective(Bankoptioncat record)
			throws SQLException {
		int rows = getSqlMap().update(
				"BANKOPTIONCAT.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	public static int updateByPrimaryKey(Bankoptioncat record) throws SQLException {
		int rows = getSqlMap().update("BANKOPTIONCAT.updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table BANKOPTIONCAT
	 * @mbggenerated
	 */
	protected static class UpdateByExampleParms extends BankoptioncatExample {
		private Object record;

		public UpdateByExampleParms(Object record, BankoptioncatExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}