package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Batchmerdaysettlehist;
import com.csii.upp.dto.generate.BatchmerdaysettlehistExample;

public class BatchmerdaysettlehistDAO extends BasePayDAO {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int countByExample(BatchmerdaysettlehistExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("BATCHMERDAYSETTLEHIST.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int deleteByExample(BatchmerdaysettlehistExample example) throws SQLException {
        int rows = getSqlMap().delete("BATCHMERDAYSETTLEHIST.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String daysettleseqnbr) throws SQLException {
        Batchmerdaysettlehist _key = new Batchmerdaysettlehist();
        _key.setDaysettleseqnbr(daysettleseqnbr);
        int rows = getSqlMap().delete("BATCHMERDAYSETTLEHIST.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static void insert(Batchmerdaysettlehist record) throws SQLException {
        getSqlMap().insert("BATCHMERDAYSETTLEHIST.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static void insertSelective(Batchmerdaysettlehist record) throws SQLException {
        getSqlMap().insert("BATCHMERDAYSETTLEHIST.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Batchmerdaysettlehist> selectByExample(BatchmerdaysettlehistExample example) throws SQLException {
        List<Batchmerdaysettlehist> list = getSqlMap().queryForList("BATCHMERDAYSETTLEHIST.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static Batchmerdaysettlehist selectByPrimaryKey(String daysettleseqnbr) throws SQLException {
        Batchmerdaysettlehist _key = new Batchmerdaysettlehist();
        _key.setDaysettleseqnbr(daysettleseqnbr);
        Batchmerdaysettlehist record = (Batchmerdaysettlehist) getSqlMap().queryForObject("BATCHMERDAYSETTLEHIST.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Batchmerdaysettlehist record, BatchmerdaysettlehistExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("BATCHMERDAYSETTLEHIST.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int updateByExample(Batchmerdaysettlehist record, BatchmerdaysettlehistExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("BATCHMERDAYSETTLEHIST.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Batchmerdaysettlehist record) throws SQLException {
        int rows = getSqlMap().update("BATCHMERDAYSETTLEHIST.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Batchmerdaysettlehist record) throws SQLException {
        int rows = getSqlMap().update("BATCHMERDAYSETTLEHIST.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BATCHMERDAYSETTLEHIST
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends BatchmerdaysettlehistExample {
        private Object record;

        public UpdateByExampleParms(Object record, BatchmerdaysettlehistExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}