package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Epaybatchcheckerror;
import com.csii.upp.dto.generate.EpaybatchcheckerrorExample;

public class EpaybatchcheckerrorDAO extends BasePayDAO {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int countByExample(EpaybatchcheckerrorExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("EPAYBATCHCHECKERROR.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int deleteByExample(EpaybatchcheckerrorExample example) throws SQLException {
        int rows = getSqlMap().delete("EPAYBATCHCHECKERROR.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String transseqnbr) throws SQLException {
        Epaybatchcheckerror _key = new Epaybatchcheckerror();
        _key.setTransseqnbr(transseqnbr);
        int rows = getSqlMap().delete("EPAYBATCHCHECKERROR.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static void insert(Epaybatchcheckerror record) throws SQLException {
        getSqlMap().insert("EPAYBATCHCHECKERROR.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static void insertSelective(Epaybatchcheckerror record) throws SQLException {
        getSqlMap().insert("EPAYBATCHCHECKERROR.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Epaybatchcheckerror> selectByExample(EpaybatchcheckerrorExample example) throws SQLException {
        List<Epaybatchcheckerror> list = getSqlMap().queryForList("EPAYBATCHCHECKERROR.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static Epaybatchcheckerror selectByPrimaryKey(String transseqnbr) throws SQLException {
        Epaybatchcheckerror _key = new Epaybatchcheckerror();
        _key.setTransseqnbr(transseqnbr);
        Epaybatchcheckerror record = (Epaybatchcheckerror) getSqlMap().queryForObject("EPAYBATCHCHECKERROR.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Epaybatchcheckerror record, EpaybatchcheckerrorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("EPAYBATCHCHECKERROR.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int updateByExample(Epaybatchcheckerror record, EpaybatchcheckerrorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("EPAYBATCHCHECKERROR.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Epaybatchcheckerror record) throws SQLException {
        int rows = getSqlMap().update("EPAYBATCHCHECKERROR.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Epaybatchcheckerror record) throws SQLException {
        int rows = getSqlMap().update("EPAYBATCHCHECKERROR.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EPAYBATCHCHECKERROR
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends EpaybatchcheckerrorExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpaybatchcheckerrorExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}