package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Onlinefileinfo;
import com.csii.upp.dto.generate.OnlinefileinfoExample;

public class OnlinefileinfoDAO extends BasePayDAO {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int countByExample(OnlinefileinfoExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("ONLINEFILEINFO.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int deleteByExample(OnlinefileinfoExample example) throws SQLException {
        int rows = getSqlMap().delete("ONLINEFILEINFO.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String filenbr, String batchnbr) throws SQLException {
        Onlinefileinfo _key = new Onlinefileinfo();
        _key.setFilenbr(filenbr);
        _key.setBatchnbr(batchnbr);
        int rows = getSqlMap().delete("ONLINEFILEINFO.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static void insert(Onlinefileinfo record) throws SQLException {
        getSqlMap().insert("ONLINEFILEINFO.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static void insertSelective(Onlinefileinfo record) throws SQLException {
        getSqlMap().insert("ONLINEFILEINFO.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Onlinefileinfo> selectByExample(OnlinefileinfoExample example) throws SQLException {
        List<Onlinefileinfo> list = getSqlMap().queryForList("ONLINEFILEINFO.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static Onlinefileinfo selectByPrimaryKey(String filenbr, String batchnbr) throws SQLException {
        Onlinefileinfo _key = new Onlinefileinfo();
        _key.setFilenbr(filenbr);
        _key.setBatchnbr(batchnbr);
        Onlinefileinfo record = (Onlinefileinfo) getSqlMap().queryForObject("ONLINEFILEINFO.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Onlinefileinfo record, OnlinefileinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINEFILEINFO.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int updateByExample(Onlinefileinfo record, OnlinefileinfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINEFILEINFO.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Onlinefileinfo record) throws SQLException {
        int rows = getSqlMap().update("ONLINEFILEINFO.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Onlinefileinfo record) throws SQLException {
        int rows = getSqlMap().update("ONLINEFILEINFO.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEFILEINFO
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends OnlinefileinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, OnlinefileinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}