package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Onlinesubtranshistall;
import com.csii.upp.dto.generate.OnlinesubtranshistallExample;

public class OnlinesubtranshistallDAO extends BasePayDAO {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int countByExample(OnlinesubtranshistallExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("ONLINESUBTRANSHISTALL.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int deleteByExample(OnlinesubtranshistallExample example) throws SQLException {
        int rows = getSqlMap().delete("ONLINESUBTRANSHISTALL.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String subtransseqnbr, String transseqnbr) throws SQLException {
        Onlinesubtranshistall _key = new Onlinesubtranshistall();
        _key.setSubtransseqnbr(subtransseqnbr);
        _key.setTransseqnbr(transseqnbr);
        int rows = getSqlMap().delete("ONLINESUBTRANSHISTALL.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static void insert(Onlinesubtranshistall record) throws SQLException {
        getSqlMap().insert("ONLINESUBTRANSHISTALL.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static void insertSelective(Onlinesubtranshistall record) throws SQLException {
        getSqlMap().insert("ONLINESUBTRANSHISTALL.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Onlinesubtranshistall> selectByExample(OnlinesubtranshistallExample example) throws SQLException {
        List<Onlinesubtranshistall> list = getSqlMap().queryForList("ONLINESUBTRANSHISTALL.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static Onlinesubtranshistall selectByPrimaryKey(String subtransseqnbr, String transseqnbr) throws SQLException {
        Onlinesubtranshistall _key = new Onlinesubtranshistall();
        _key.setSubtransseqnbr(subtransseqnbr);
        _key.setTransseqnbr(transseqnbr);
        Onlinesubtranshistall record = (Onlinesubtranshistall) getSqlMap().queryForObject("ONLINESUBTRANSHISTALL.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Onlinesubtranshistall record, OnlinesubtranshistallExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINESUBTRANSHISTALL.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByExample(Onlinesubtranshistall record, OnlinesubtranshistallExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINESUBTRANSHISTALL.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Onlinesubtranshistall record) throws SQLException {
        int rows = getSqlMap().update("ONLINESUBTRANSHISTALL.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Onlinesubtranshistall record) throws SQLException {
        int rows = getSqlMap().update("ONLINESUBTRANSHISTALL.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINESUBTRANSHISTALL
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends OnlinesubtranshistallExample {
        private Object record;

        public UpdateByExampleParms(Object record, OnlinesubtranshistallExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}