package com.csii.upp.dao.generate;

import java.sql.SQLException;
import java.util.List;

import com.csii.upp.dao.BasePayDAO;
import com.csii.upp.dto.generate.Onlinereqfiletrans;
import com.csii.upp.dto.generate.OnlinereqfiletransExample;

public class OnlinereqfiletransDAO extends BasePayDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int countByExample(OnlinereqfiletransExample example) throws SQLException {
        Integer count = (Integer)  getSqlMap().queryForObject("ONLINEREQFILETRANS.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int deleteByExample(OnlinereqfiletransExample example) throws SQLException {
        int rows = getSqlMap().delete("ONLINEREQFILETRANS.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int deleteByPrimaryKey(String merseqnbr, String filenbr, String batchnbr) throws SQLException {
        Onlinereqfiletrans _key = new Onlinereqfiletrans();
        _key.setMerseqnbr(merseqnbr);
        _key.setFilenbr(filenbr);
        _key.setBatchnbr(batchnbr);
        int rows = getSqlMap().delete("ONLINEREQFILETRANS.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static void insert(Onlinereqfiletrans record) throws SQLException {
        getSqlMap().insert("ONLINEREQFILETRANS.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static void insertSelective(Onlinereqfiletrans record) throws SQLException {
        getSqlMap().insert("ONLINEREQFILETRANS.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public static List<Onlinereqfiletrans> selectByExample(OnlinereqfiletransExample example) throws SQLException {
        List<Onlinereqfiletrans> list = getSqlMap().queryForList("ONLINEREQFILETRANS.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static Onlinereqfiletrans selectByPrimaryKey(String merseqnbr, String filenbr, String batchnbr) throws SQLException {
        Onlinereqfiletrans _key = new Onlinereqfiletrans();
        _key.setMerseqnbr(merseqnbr);
        _key.setFilenbr(filenbr);
        _key.setBatchnbr(batchnbr);
        Onlinereqfiletrans record = (Onlinereqfiletrans) getSqlMap().queryForObject("ONLINEREQFILETRANS.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int updateByExampleSelective(Onlinereqfiletrans record, OnlinereqfiletransExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINEREQFILETRANS.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int updateByExample(Onlinereqfiletrans record, OnlinereqfiletransExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMap().update("ONLINEREQFILETRANS.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKeySelective(Onlinereqfiletrans record) throws SQLException {
        int rows = getSqlMap().update("ONLINEREQFILETRANS.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    public static int updateByPrimaryKey(Onlinereqfiletrans record) throws SQLException {
        int rows = getSqlMap().update("ONLINEREQFILETRANS.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEREQFILETRANS
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends OnlinereqfiletransExample {
        private Object record;

        public UpdateByExampleParms(Object record, OnlinereqfiletransExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}