package com.csii.upp.dto.generate;

import java.math.BigDecimal;
import java.util.Date;

public class Epaybatchcheckerrorhist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    private String transseqnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    private String downsystransnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.TRANSDATE
     *
     * @mbggenerated
     */
    private Date transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSDATE
     *
     * @mbggenerated
     */
    private Date downsystransdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    private String custcifnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    private String payeracctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeraccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeracctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    private String payeracctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    private String payeeacctnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    private String payeeacctdeptnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    private String payeeaccttypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    private String payeeacctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    private String payeracctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    private String payeeacctkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    private String payercardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    private String payeecardtypcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.TRANSCODE
     *
     * @mbggenerated
     */
    private String transcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.TRANSAMT
     *
     * @mbggenerated
     */
    private BigDecimal transamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    private String currencycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    private String transstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.CHECKERRORTYP
     *
     * @mbggenerated
     */
    private String checkerrortyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    private String departmentnbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    private Date datelastmaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DEALDATE
     *
     * @mbggenerated
     */
    private Date dealdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.DEALSTATUS
     *
     * @mbggenerated
     */
    private String dealstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPAYBATCHCHECKERRORHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    private String paytypcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.TRANSSEQNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public String getTransseqnbr() {
        return transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.TRANSSEQNBR
     *
     * @param transseqnbr the value for EPAYBATCHCHECKERRORHIST.TRANSSEQNBR
     *
     * @mbggenerated
     */
    public void setTransseqnbr(String transseqnbr) {
        this.transseqnbr = transseqnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public String getDownsystransnbr() {
        return downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSNBR
     *
     * @param downsystransnbr the value for EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSNBR
     *
     * @mbggenerated
     */
    public void setDownsystransnbr(String downsystransnbr) {
        this.downsystransnbr = downsystransnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.TRANSDATE
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.TRANSDATE
     *
     * @mbggenerated
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.TRANSDATE
     *
     * @param transdate the value for EPAYBATCHCHECKERRORHIST.TRANSDATE
     *
     * @mbggenerated
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSDATE
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSDATE
     *
     * @mbggenerated
     */
    public Date getDownsystransdate() {
        return downsystransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSDATE
     *
     * @param downsystransdate the value for EPAYBATCHCHECKERRORHIST.DOWNSYSTRANSDATE
     *
     * @mbggenerated
     */
    public void setDownsystransdate(Date downsystransdate) {
        this.downsystransdate = downsystransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.CUSTCIFNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public String getCustcifnbr() {
        return custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.CUSTCIFNBR
     *
     * @param custcifnbr the value for EPAYBATCHCHECKERRORHIST.CUSTCIFNBR
     *
     * @mbggenerated
     */
    public void setCustcifnbr(String custcifnbr) {
        this.custcifnbr = custcifnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctnbr() {
        return payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNBR
     *
     * @param payeracctnbr the value for EPAYBATCHCHECKERRORHIST.PAYERACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctnbr(String payeracctnbr) {
        this.payeracctnbr = payeracctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTTYPCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeraccttypcd() {
        return payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTTYPCD
     *
     * @param payeraccttypcd the value for EPAYBATCHCHECKERRORHIST.PAYERACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeraccttypcd(String payeraccttypcd) {
        this.payeraccttypcd = payeraccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTDEPTNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeracctdeptnbr() {
        return payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTDEPTNBR
     *
     * @param payeracctdeptnbr the value for EPAYBATCHCHECKERRORHIST.PAYERACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeracctdeptnbr(String payeracctdeptnbr) {
        this.payeracctdeptnbr = payeracctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNAME
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeracctname() {
        return payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTNAME
     *
     * @param payeracctname the value for EPAYBATCHCHECKERRORHIST.PAYERACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeracctname(String payeracctname) {
        this.payeracctname = payeracctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctnbr() {
        return payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNBR
     *
     * @param payeeacctnbr the value for EPAYBATCHCHECKERRORHIST.PAYEEACCTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctnbr(String payeeacctnbr) {
        this.payeeacctnbr = payeeacctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTDEPTNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public String getPayeeacctdeptnbr() {
        return payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTDEPTNBR
     *
     * @param payeeacctdeptnbr the value for EPAYBATCHCHECKERRORHIST.PAYEEACCTDEPTNBR
     *
     * @mbggenerated
     */
    public void setPayeeacctdeptnbr(String payeeacctdeptnbr) {
        this.payeeacctdeptnbr = payeeacctdeptnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTTYPCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public String getPayeeaccttypcd() {
        return payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTTYPCD
     *
     * @param payeeaccttypcd the value for EPAYBATCHCHECKERRORHIST.PAYEEACCTTYPCD
     *
     * @mbggenerated
     */
    public void setPayeeaccttypcd(String payeeaccttypcd) {
        this.payeeaccttypcd = payeeaccttypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNAME
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public String getPayeeacctname() {
        return payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTNAME
     *
     * @param payeeacctname the value for EPAYBATCHCHECKERRORHIST.PAYEEACCTNAME
     *
     * @mbggenerated
     */
    public void setPayeeacctname(String payeeacctname) {
        this.payeeacctname = payeeacctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTKIND
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeracctkind() {
        return payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERACCTKIND
     *
     * @param payeracctkind the value for EPAYBATCHCHECKERRORHIST.PAYERACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeracctkind(String payeracctkind) {
        this.payeracctkind = payeracctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTKIND
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public String getPayeeacctkind() {
        return payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEEACCTKIND
     *
     * @param payeeacctkind the value for EPAYBATCHCHECKERRORHIST.PAYEEACCTKIND
     *
     * @mbggenerated
     */
    public void setPayeeacctkind(String payeeacctkind) {
        this.payeeacctkind = payeeacctkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYERCARDTYPCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayercardtypcd() {
        return payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYERCARDTYPCD
     *
     * @param payercardtypcd the value for EPAYBATCHCHECKERRORHIST.PAYERCARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayercardtypcd(String payercardtypcd) {
        this.payercardtypcd = payercardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYEECARDTYPCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public String getPayeecardtypcd() {
        return payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYEECARDTYPCD
     *
     * @param payeecardtypcd the value for EPAYBATCHCHECKERRORHIST.PAYEECARDTYPCD
     *
     * @mbggenerated
     */
    public void setPayeecardtypcd(String payeecardtypcd) {
        this.payeecardtypcd = payeecardtypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.TRANSCODE
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.TRANSCODE
     *
     * @mbggenerated
     */
    public String getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.TRANSCODE
     *
     * @param transcode the value for EPAYBATCHCHECKERRORHIST.TRANSCODE
     *
     * @mbggenerated
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.TRANSAMT
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.TRANSAMT
     *
     * @mbggenerated
     */
    public BigDecimal getTransamt() {
        return transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.TRANSAMT
     *
     * @param transamt the value for EPAYBATCHCHECKERRORHIST.TRANSAMT
     *
     * @mbggenerated
     */
    public void setTransamt(BigDecimal transamt) {
        this.transamt = transamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.CURRENCYCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    public String getCurrencycd() {
        return currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.CURRENCYCD
     *
     * @param currencycd the value for EPAYBATCHCHECKERRORHIST.CURRENCYCD
     *
     * @mbggenerated
     */
    public void setCurrencycd(String currencycd) {
        this.currencycd = currencycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.TRANSSTATUS
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    public String getTransstatus() {
        return transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.TRANSSTATUS
     *
     * @param transstatus the value for EPAYBATCHCHECKERRORHIST.TRANSSTATUS
     *
     * @mbggenerated
     */
    public void setTransstatus(String transstatus) {
        this.transstatus = transstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.CHECKERRORTYP
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.CHECKERRORTYP
     *
     * @mbggenerated
     */
    public String getCheckerrortyp() {
        return checkerrortyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.CHECKERRORTYP
     *
     * @param checkerrortyp the value for EPAYBATCHCHECKERRORHIST.CHECKERRORTYP
     *
     * @mbggenerated
     */
    public void setCheckerrortyp(String checkerrortyp) {
        this.checkerrortyp = checkerrortyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DEPARTMENTNBR
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public String getDepartmentnbr() {
        return departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DEPARTMENTNBR
     *
     * @param departmentnbr the value for EPAYBATCHCHECKERRORHIST.DEPARTMENTNBR
     *
     * @mbggenerated
     */
    public void setDepartmentnbr(String departmentnbr) {
        this.departmentnbr = departmentnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DATELASTMAINT
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    public Date getDatelastmaint() {
        return datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DATELASTMAINT
     *
     * @param datelastmaint the value for EPAYBATCHCHECKERRORHIST.DATELASTMAINT
     *
     * @mbggenerated
     */
    protected void setDatelastmaint(Date datelastmaint) {
        this.datelastmaint = datelastmaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DEALDATE
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DEALDATE
     *
     * @mbggenerated
     */
    public Date getDealdate() {
        return dealdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DEALDATE
     *
     * @param dealdate the value for EPAYBATCHCHECKERRORHIST.DEALDATE
     *
     * @mbggenerated
     */
    public void setDealdate(Date dealdate) {
        this.dealdate = dealdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.DEALSTATUS
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.DEALSTATUS
     *
     * @mbggenerated
     */
    public String getDealstatus() {
        return dealstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.DEALSTATUS
     *
     * @param dealstatus the value for EPAYBATCHCHECKERRORHIST.DEALSTATUS
     *
     * @mbggenerated
     */
    public void setDealstatus(String dealstatus) {
        this.dealstatus = dealstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPAYBATCHCHECKERRORHIST.PAYTYPCD
     *
     * @return the value of EPAYBATCHCHECKERRORHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    public String getPaytypcd() {
        return paytypcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPAYBATCHCHECKERRORHIST.PAYTYPCD
     *
     * @param paytypcd the value for EPAYBATCHCHECKERRORHIST.PAYTYPCD
     *
     * @mbggenerated
     */
    public void setPaytypcd(String paytypcd) {
        this.paytypcd = paytypcd;
    }
}