package com.csii.upp.qrcodeplatform.generate.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UpperchannelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public UpperchannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChannelnbrIsNull() {
            addCriterion("CHANNELNBR is null");
            return (Criteria) this;
        }

        public Criteria andChannelnbrIsNotNull() {
            addCriterion("CHANNELNBR is not null");
            return (Criteria) this;
        }

        public Criteria andChannelnbrEqualTo(String value) {
            addCriterion("CHANNELNBR =", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrNotEqualTo(String value) {
            addCriterion("CHANNELNBR <>", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrGreaterThan(String value) {
            addCriterion("CHANNELNBR >", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNELNBR >=", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrLessThan(String value) {
            addCriterion("CHANNELNBR <", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrLessThanOrEqualTo(String value) {
            addCriterion("CHANNELNBR <=", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrLike(String value) {
            addCriterion("CHANNELNBR like", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrNotLike(String value) {
            addCriterion("CHANNELNBR not like", value, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrIn(List<String> values) {
            addCriterion("CHANNELNBR in", values, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrNotIn(List<String> values) {
            addCriterion("CHANNELNBR not in", values, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrBetween(String value1, String value2) {
            addCriterion("CHANNELNBR between", value1, value2, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andChannelnbrNotBetween(String value1, String value2) {
            addCriterion("CHANNELNBR not between", value1, value2, "channelnbr");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagIsNull() {
            addCriterion("CHECKPUSHFLAG is null");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagIsNotNull() {
            addCriterion("CHECKPUSHFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagEqualTo(String value) {
            addCriterion("CHECKPUSHFLAG =", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagNotEqualTo(String value) {
            addCriterion("CHECKPUSHFLAG <>", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagGreaterThan(String value) {
            addCriterion("CHECKPUSHFLAG >", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKPUSHFLAG >=", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagLessThan(String value) {
            addCriterion("CHECKPUSHFLAG <", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagLessThanOrEqualTo(String value) {
            addCriterion("CHECKPUSHFLAG <=", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagLike(String value) {
            addCriterion("CHECKPUSHFLAG like", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagNotLike(String value) {
            addCriterion("CHECKPUSHFLAG not like", value, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagIn(List<String> values) {
            addCriterion("CHECKPUSHFLAG in", values, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagNotIn(List<String> values) {
            addCriterion("CHECKPUSHFLAG not in", values, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagBetween(String value1, String value2) {
            addCriterion("CHECKPUSHFLAG between", value1, value2, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andCheckpushflagNotBetween(String value1, String value2) {
            addCriterion("CHECKPUSHFLAG not between", value1, value2, "checkpushflag");
            return (Criteria) this;
        }

        public Criteria andClearflagIsNull() {
            addCriterion("CLEARFLAG is null");
            return (Criteria) this;
        }

        public Criteria andClearflagIsNotNull() {
            addCriterion("CLEARFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andClearflagEqualTo(String value) {
            addCriterion("CLEARFLAG =", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagNotEqualTo(String value) {
            addCriterion("CLEARFLAG <>", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagGreaterThan(String value) {
            addCriterion("CLEARFLAG >", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagGreaterThanOrEqualTo(String value) {
            addCriterion("CLEARFLAG >=", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagLessThan(String value) {
            addCriterion("CLEARFLAG <", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagLessThanOrEqualTo(String value) {
            addCriterion("CLEARFLAG <=", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagLike(String value) {
            addCriterion("CLEARFLAG like", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagNotLike(String value) {
            addCriterion("CLEARFLAG not like", value, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagIn(List<String> values) {
            addCriterion("CLEARFLAG in", values, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagNotIn(List<String> values) {
            addCriterion("CLEARFLAG not in", values, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagBetween(String value1, String value2) {
            addCriterion("CLEARFLAG between", value1, value2, "clearflag");
            return (Criteria) this;
        }

        public Criteria andClearflagNotBetween(String value1, String value2) {
            addCriterion("CLEARFLAG not between", value1, value2, "clearflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagIsNull() {
            addCriterion("NOTICEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andNoticeflagIsNotNull() {
            addCriterion("NOTICEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeflagEqualTo(String value) {
            addCriterion("NOTICEFLAG =", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagNotEqualTo(String value) {
            addCriterion("NOTICEFLAG <>", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagGreaterThan(String value) {
            addCriterion("NOTICEFLAG >", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICEFLAG >=", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagLessThan(String value) {
            addCriterion("NOTICEFLAG <", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagLessThanOrEqualTo(String value) {
            addCriterion("NOTICEFLAG <=", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagLike(String value) {
            addCriterion("NOTICEFLAG like", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagNotLike(String value) {
            addCriterion("NOTICEFLAG not like", value, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagIn(List<String> values) {
            addCriterion("NOTICEFLAG in", values, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagNotIn(List<String> values) {
            addCriterion("NOTICEFLAG not in", values, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagBetween(String value1, String value2) {
            addCriterion("NOTICEFLAG between", value1, value2, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andNoticeflagNotBetween(String value1, String value2) {
            addCriterion("NOTICEFLAG not between", value1, value2, "noticeflag");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNull() {
            addCriterion("DATELASTMAINT is null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIsNotNull() {
            addCriterion("DATELASTMAINT is not null");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintEqualTo(Date value) {
            addCriterion("DATELASTMAINT =", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotEqualTo(Date value) {
            addCriterion("DATELASTMAINT <>", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThan(Date value) {
            addCriterion("DATELASTMAINT >", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintGreaterThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT >=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThan(Date value) {
            addCriterion("DATELASTMAINT <", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintLessThanOrEqualTo(Date value) {
            addCriterion("DATELASTMAINT <=", value, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintIn(List<Date> values) {
            addCriterion("DATELASTMAINT in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotIn(List<Date> values) {
            addCriterion("DATELASTMAINT not in", values, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }

        public Criteria andDatelastmaintNotBetween(Date value1, Date value2) {
            addCriterion("DATELASTMAINT not between", value1, value2, "datelastmaint");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upperchannel
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upperchannel
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}