package com.csii.upp.qrcodeplatform.generate.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MarketingactivitiesruleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public MarketingactivitiesruleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMarketactiveidIsNull() {
            addCriterion("MARKETACTIVEID is null");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidIsNotNull() {
            addCriterion("MARKETACTIVEID is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidEqualTo(String value) {
            addCriterion("MARKETACTIVEID =", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidNotEqualTo(String value) {
            addCriterion("MARKETACTIVEID <>", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidGreaterThan(String value) {
            addCriterion("MARKETACTIVEID >", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVEID >=", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidLessThan(String value) {
            addCriterion("MARKETACTIVEID <", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVEID <=", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidLike(String value) {
            addCriterion("MARKETACTIVEID like", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidNotLike(String value) {
            addCriterion("MARKETACTIVEID not like", value, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidIn(List<String> values) {
            addCriterion("MARKETACTIVEID in", values, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidNotIn(List<String> values) {
            addCriterion("MARKETACTIVEID not in", values, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidBetween(String value1, String value2) {
            addCriterion("MARKETACTIVEID between", value1, value2, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMarketactiveidNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVEID not between", value1, value2, "marketactiveid");
            return (Criteria) this;
        }

        public Criteria andMernbrIsNull() {
            addCriterion("MERNBR is null");
            return (Criteria) this;
        }

        public Criteria andMernbrIsNotNull() {
            addCriterion("MERNBR is not null");
            return (Criteria) this;
        }

        public Criteria andMernbrEqualTo(String value) {
            addCriterion("MERNBR =", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrNotEqualTo(String value) {
            addCriterion("MERNBR <>", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrGreaterThan(String value) {
            addCriterion("MERNBR >", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrGreaterThanOrEqualTo(String value) {
            addCriterion("MERNBR >=", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrLessThan(String value) {
            addCriterion("MERNBR <", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrLessThanOrEqualTo(String value) {
            addCriterion("MERNBR <=", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrLike(String value) {
            addCriterion("MERNBR like", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrNotLike(String value) {
            addCriterion("MERNBR not like", value, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrIn(List<String> values) {
            addCriterion("MERNBR in", values, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrNotIn(List<String> values) {
            addCriterion("MERNBR not in", values, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrBetween(String value1, String value2) {
            addCriterion("MERNBR between", value1, value2, "mernbr");
            return (Criteria) this;
        }

        public Criteria andMernbrNotBetween(String value1, String value2) {
            addCriterion("MERNBR not between", value1, value2, "mernbr");
            return (Criteria) this;
        }

        public Criteria andShopnumberIsNull() {
            addCriterion("SHOPNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andShopnumberIsNotNull() {
            addCriterion("SHOPNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andShopnumberEqualTo(String value) {
            addCriterion("SHOPNUMBER =", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberNotEqualTo(String value) {
            addCriterion("SHOPNUMBER <>", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberGreaterThan(String value) {
            addCriterion("SHOPNUMBER >", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberGreaterThanOrEqualTo(String value) {
            addCriterion("SHOPNUMBER >=", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberLessThan(String value) {
            addCriterion("SHOPNUMBER <", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberLessThanOrEqualTo(String value) {
            addCriterion("SHOPNUMBER <=", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberLike(String value) {
            addCriterion("SHOPNUMBER like", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberNotLike(String value) {
            addCriterion("SHOPNUMBER not like", value, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberIn(List<String> values) {
            addCriterion("SHOPNUMBER in", values, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberNotIn(List<String> values) {
            addCriterion("SHOPNUMBER not in", values, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberBetween(String value1, String value2) {
            addCriterion("SHOPNUMBER between", value1, value2, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andShopnumberNotBetween(String value1, String value2) {
            addCriterion("SHOPNUMBER not between", value1, value2, "shopnumber");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameIsNull() {
            addCriterion("MARKETACTIVENAME is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameIsNotNull() {
            addCriterion("MARKETACTIVENAME is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameEqualTo(String value) {
            addCriterion("MARKETACTIVENAME =", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameNotEqualTo(String value) {
            addCriterion("MARKETACTIVENAME <>", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameGreaterThan(String value) {
            addCriterion("MARKETACTIVENAME >", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVENAME >=", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameLessThan(String value) {
            addCriterion("MARKETACTIVENAME <", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVENAME <=", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameLike(String value) {
            addCriterion("MARKETACTIVENAME like", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameNotLike(String value) {
            addCriterion("MARKETACTIVENAME not like", value, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameIn(List<String> values) {
            addCriterion("MARKETACTIVENAME in", values, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameNotIn(List<String> values) {
            addCriterion("MARKETACTIVENAME not in", values, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameBetween(String value1, String value2) {
            addCriterion("MARKETACTIVENAME between", value1, value2, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivenameNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVENAME not between", value1, value2, "marketactivename");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontIsNull() {
            addCriterion("MARKETACTIVECONT is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontIsNotNull() {
            addCriterion("MARKETACTIVECONT is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontEqualTo(String value) {
            addCriterion("MARKETACTIVECONT =", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontNotEqualTo(String value) {
            addCriterion("MARKETACTIVECONT <>", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontGreaterThan(String value) {
            addCriterion("MARKETACTIVECONT >", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVECONT >=", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontLessThan(String value) {
            addCriterion("MARKETACTIVECONT <", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVECONT <=", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontLike(String value) {
            addCriterion("MARKETACTIVECONT like", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontNotLike(String value) {
            addCriterion("MARKETACTIVECONT not like", value, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontIn(List<String> values) {
            addCriterion("MARKETACTIVECONT in", values, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontNotIn(List<String> values) {
            addCriterion("MARKETACTIVECONT not in", values, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontBetween(String value1, String value2) {
            addCriterion("MARKETACTIVECONT between", value1, value2, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivecontNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVECONT not between", value1, value2, "marketactivecont");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeIsNull() {
            addCriterion("MARKETACTIVETYPE is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeIsNotNull() {
            addCriterion("MARKETACTIVETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeEqualTo(String value) {
            addCriterion("MARKETACTIVETYPE =", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeNotEqualTo(String value) {
            addCriterion("MARKETACTIVETYPE <>", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeGreaterThan(String value) {
            addCriterion("MARKETACTIVETYPE >", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVETYPE >=", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeLessThan(String value) {
            addCriterion("MARKETACTIVETYPE <", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVETYPE <=", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeLike(String value) {
            addCriterion("MARKETACTIVETYPE like", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeNotLike(String value) {
            addCriterion("MARKETACTIVETYPE not like", value, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeIn(List<String> values) {
            addCriterion("MARKETACTIVETYPE in", values, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeNotIn(List<String> values) {
            addCriterion("MARKETACTIVETYPE not in", values, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeBetween(String value1, String value2) {
            addCriterion("MARKETACTIVETYPE between", value1, value2, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andMarketactivetypeNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVETYPE not between", value1, value2, "marketactivetype");
            return (Criteria) this;
        }

        public Criteria andConditionparamIsNull() {
            addCriterion("CONDITIONPARAM is null");
            return (Criteria) this;
        }

        public Criteria andConditionparamIsNotNull() {
            addCriterion("CONDITIONPARAM is not null");
            return (Criteria) this;
        }

        public Criteria andConditionparamEqualTo(String value) {
            addCriterion("CONDITIONPARAM =", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamNotEqualTo(String value) {
            addCriterion("CONDITIONPARAM <>", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamGreaterThan(String value) {
            addCriterion("CONDITIONPARAM >", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamGreaterThanOrEqualTo(String value) {
            addCriterion("CONDITIONPARAM >=", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamLessThan(String value) {
            addCriterion("CONDITIONPARAM <", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamLessThanOrEqualTo(String value) {
            addCriterion("CONDITIONPARAM <=", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamLike(String value) {
            addCriterion("CONDITIONPARAM like", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamNotLike(String value) {
            addCriterion("CONDITIONPARAM not like", value, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamIn(List<String> values) {
            addCriterion("CONDITIONPARAM in", values, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamNotIn(List<String> values) {
            addCriterion("CONDITIONPARAM not in", values, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamBetween(String value1, String value2) {
            addCriterion("CONDITIONPARAM between", value1, value2, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andConditionparamNotBetween(String value1, String value2) {
            addCriterion("CONDITIONPARAM not between", value1, value2, "conditionparam");
            return (Criteria) this;
        }

        public Criteria andCalcuruleIsNull() {
            addCriterion("CALCURULE is null");
            return (Criteria) this;
        }

        public Criteria andCalcuruleIsNotNull() {
            addCriterion("CALCURULE is not null");
            return (Criteria) this;
        }

        public Criteria andCalcuruleEqualTo(String value) {
            addCriterion("CALCURULE =", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleNotEqualTo(String value) {
            addCriterion("CALCURULE <>", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleGreaterThan(String value) {
            addCriterion("CALCURULE >", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleGreaterThanOrEqualTo(String value) {
            addCriterion("CALCURULE >=", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleLessThan(String value) {
            addCriterion("CALCURULE <", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleLessThanOrEqualTo(String value) {
            addCriterion("CALCURULE <=", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleLike(String value) {
            addCriterion("CALCURULE like", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleNotLike(String value) {
            addCriterion("CALCURULE not like", value, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleIn(List<String> values) {
            addCriterion("CALCURULE in", values, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleNotIn(List<String> values) {
            addCriterion("CALCURULE not in", values, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleBetween(String value1, String value2) {
            addCriterion("CALCURULE between", value1, value2, "calcurule");
            return (Criteria) this;
        }

        public Criteria andCalcuruleNotBetween(String value1, String value2) {
            addCriterion("CALCURULE not between", value1, value2, "calcurule");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterIsNull() {
            addCriterion("MARKETACTIVECOSTER is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterIsNotNull() {
            addCriterion("MARKETACTIVECOSTER is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterEqualTo(String value) {
            addCriterion("MARKETACTIVECOSTER =", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterNotEqualTo(String value) {
            addCriterion("MARKETACTIVECOSTER <>", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterGreaterThan(String value) {
            addCriterion("MARKETACTIVECOSTER >", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVECOSTER >=", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterLessThan(String value) {
            addCriterion("MARKETACTIVECOSTER <", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVECOSTER <=", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterLike(String value) {
            addCriterion("MARKETACTIVECOSTER like", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterNotLike(String value) {
            addCriterion("MARKETACTIVECOSTER not like", value, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterIn(List<String> values) {
            addCriterion("MARKETACTIVECOSTER in", values, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterNotIn(List<String> values) {
            addCriterion("MARKETACTIVECOSTER not in", values, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterBetween(String value1, String value2) {
            addCriterion("MARKETACTIVECOSTER between", value1, value2, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivecosterNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVECOSTER not between", value1, value2, "marketactivecoster");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateIsNull() {
            addCriterion("MARKETACTIVESTARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateIsNotNull() {
            addCriterion("MARKETACTIVESTARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE =", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE <>", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateGreaterThan(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE >", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE >=", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateLessThan(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE <", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE <=", value, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateIn(List<Date> values) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE in", values, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE not in", values, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE between", value1, value2, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactivestartdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MARKETACTIVESTARTDATE not between", value1, value2, "marketactivestartdate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateIsNull() {
            addCriterion("MARKETACTIVEENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateIsNotNull() {
            addCriterion("MARKETACTIVEENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE =", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE <>", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateGreaterThan(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE >", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE >=", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateLessThan(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE <", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE <=", value, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateIn(List<Date> values) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE in", values, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE not in", values, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE between", value1, value2, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactiveenddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MARKETACTIVEENDDATE not between", value1, value2, "marketactiveenddate");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountIsNull() {
            addCriterion("MARKETACTIVEMAXCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountIsNotNull() {
            addCriterion("MARKETACTIVEMAXCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT =", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountNotEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT <>", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountGreaterThan(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT >", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT >=", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountLessThan(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT <", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXCOUNT <=", value, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountIn(List<BigDecimal> values) {
            addCriterion("MARKETACTIVEMAXCOUNT in", values, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountNotIn(List<BigDecimal> values) {
            addCriterion("MARKETACTIVEMAXCOUNT not in", values, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKETACTIVEMAXCOUNT between", value1, value2, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxcountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKETACTIVEMAXCOUNT not between", value1, value2, "marketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtIsNull() {
            addCriterion("MARKETACTIVEMAXAMT is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtIsNotNull() {
            addCriterion("MARKETACTIVEMAXAMT is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT =", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtNotEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT <>", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtGreaterThan(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT >", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT >=", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtLessThan(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT <", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKETACTIVEMAXAMT <=", value, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtIn(List<BigDecimal> values) {
            addCriterion("MARKETACTIVEMAXAMT in", values, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtNotIn(List<BigDecimal> values) {
            addCriterion("MARKETACTIVEMAXAMT not in", values, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKETACTIVEMAXAMT between", value1, value2, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andMarketactivemaxamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKETACTIVEMAXAMT not between", value1, value2, "marketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesIsNull() {
            addCriterion("TOTALCUMULATIVETIMES is null");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesIsNotNull() {
            addCriterion("TOTALCUMULATIVETIMES is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES =", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES <>", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesGreaterThan(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES >", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES >=", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesLessThan(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES <", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVETIMES <=", value, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesIn(List<BigDecimal> values) {
            addCriterion("TOTALCUMULATIVETIMES in", values, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCUMULATIVETIMES not in", values, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCUMULATIVETIMES between", value1, value2, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativetimesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCUMULATIVETIMES not between", value1, value2, "totalcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtIsNull() {
            addCriterion("TOTALCUMULATIVEAMT is null");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtIsNotNull() {
            addCriterion("TOTALCUMULATIVEAMT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT =", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT <>", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtGreaterThan(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT >", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT >=", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtLessThan(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT <", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCUMULATIVEAMT <=", value, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtIn(List<BigDecimal> values) {
            addCriterion("TOTALCUMULATIVEAMT in", values, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCUMULATIVEAMT not in", values, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCUMULATIVEAMT between", value1, value2, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andTotalcumulativeamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCUMULATIVEAMT not between", value1, value2, "totalcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountIsNull() {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountIsNotNull() {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT =", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountNotEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT <>", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountGreaterThan(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT >", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT >=", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountLessThan(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT <", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT <=", value, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountIn(List<BigDecimal> values) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT in", values, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountNotIn(List<BigDecimal> values) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT not in", values, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT between", value1, value2, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxcountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODMARKETACTIVEMAXCOUNT not between", value1, value2, "periodmarketactivemaxcount");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtIsNull() {
            addCriterion("PERIODMARKETACTIVEMAXAMT is null");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtIsNotNull() {
            addCriterion("PERIODMARKETACTIVEMAXAMT is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT =", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtNotEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT <>", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtGreaterThan(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT >", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT >=", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtLessThan(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT <", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODMARKETACTIVEMAXAMT <=", value, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtIn(List<BigDecimal> values) {
            addCriterion("PERIODMARKETACTIVEMAXAMT in", values, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtNotIn(List<BigDecimal> values) {
            addCriterion("PERIODMARKETACTIVEMAXAMT not in", values, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODMARKETACTIVEMAXAMT between", value1, value2, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodmarketactivemaxamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODMARKETACTIVEMAXAMT not between", value1, value2, "periodmarketactivemaxamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesIsNull() {
            addCriterion("PERIODCUMULATIVETIMES is null");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesIsNotNull() {
            addCriterion("PERIODCUMULATIVETIMES is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES =", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesNotEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES <>", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesGreaterThan(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES >", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES >=", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesLessThan(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES <", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVETIMES <=", value, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesIn(List<BigDecimal> values) {
            addCriterion("PERIODCUMULATIVETIMES in", values, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesNotIn(List<BigDecimal> values) {
            addCriterion("PERIODCUMULATIVETIMES not in", values, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODCUMULATIVETIMES between", value1, value2, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativetimesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODCUMULATIVETIMES not between", value1, value2, "periodcumulativetimes");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtIsNull() {
            addCriterion("PERIODCUMULATIVEAMT is null");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtIsNotNull() {
            addCriterion("PERIODCUMULATIVEAMT is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT =", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtNotEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT <>", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtGreaterThan(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT >", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT >=", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtLessThan(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT <", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERIODCUMULATIVEAMT <=", value, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtIn(List<BigDecimal> values) {
            addCriterion("PERIODCUMULATIVEAMT in", values, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtNotIn(List<BigDecimal> values) {
            addCriterion("PERIODCUMULATIVEAMT not in", values, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODCUMULATIVEAMT between", value1, value2, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodcumulativeamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERIODCUMULATIVEAMT not between", value1, value2, "periodcumulativeamt");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateIsNull() {
            addCriterion("PERIODACTIVEDATE is null");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateIsNotNull() {
            addCriterion("PERIODACTIVEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateEqualTo(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE =", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE <>", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateGreaterThan(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE >", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE >=", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateLessThan(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE <", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PERIODACTIVEDATE <=", value, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateIn(List<Date> values) {
            addCriterionForJDBCDate("PERIODACTIVEDATE in", values, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PERIODACTIVEDATE not in", values, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PERIODACTIVEDATE between", value1, value2, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PERIODACTIVEDATE not between", value1, value2, "periodactivedate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateIsNull() {
            addCriterion("PERIODACTIVESTARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateIsNotNull() {
            addCriterion("PERIODACTIVESTARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateEqualTo(String value) {
            addCriterion("PERIODACTIVESTARTDATE =", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateNotEqualTo(String value) {
            addCriterion("PERIODACTIVESTARTDATE <>", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateGreaterThan(String value) {
            addCriterion("PERIODACTIVESTARTDATE >", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateGreaterThanOrEqualTo(String value) {
            addCriterion("PERIODACTIVESTARTDATE >=", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateLessThan(String value) {
            addCriterion("PERIODACTIVESTARTDATE <", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateLessThanOrEqualTo(String value) {
            addCriterion("PERIODACTIVESTARTDATE <=", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateLike(String value) {
            addCriterion("PERIODACTIVESTARTDATE like", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateNotLike(String value) {
            addCriterion("PERIODACTIVESTARTDATE not like", value, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateIn(List<String> values) {
            addCriterion("PERIODACTIVESTARTDATE in", values, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateNotIn(List<String> values) {
            addCriterion("PERIODACTIVESTARTDATE not in", values, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateBetween(String value1, String value2) {
            addCriterion("PERIODACTIVESTARTDATE between", value1, value2, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactivestartdateNotBetween(String value1, String value2) {
            addCriterion("PERIODACTIVESTARTDATE not between", value1, value2, "periodactivestartdate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateIsNull() {
            addCriterion("PERIODACTIVEENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateIsNotNull() {
            addCriterion("PERIODACTIVEENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateEqualTo(String value) {
            addCriterion("PERIODACTIVEENDDATE =", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateNotEqualTo(String value) {
            addCriterion("PERIODACTIVEENDDATE <>", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateGreaterThan(String value) {
            addCriterion("PERIODACTIVEENDDATE >", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateGreaterThanOrEqualTo(String value) {
            addCriterion("PERIODACTIVEENDDATE >=", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateLessThan(String value) {
            addCriterion("PERIODACTIVEENDDATE <", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateLessThanOrEqualTo(String value) {
            addCriterion("PERIODACTIVEENDDATE <=", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateLike(String value) {
            addCriterion("PERIODACTIVEENDDATE like", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateNotLike(String value) {
            addCriterion("PERIODACTIVEENDDATE not like", value, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateIn(List<String> values) {
            addCriterion("PERIODACTIVEENDDATE in", values, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateNotIn(List<String> values) {
            addCriterion("PERIODACTIVEENDDATE not in", values, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateBetween(String value1, String value2) {
            addCriterion("PERIODACTIVEENDDATE between", value1, value2, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andPeriodactiveenddateNotBetween(String value1, String value2) {
            addCriterion("PERIODACTIVEENDDATE not between", value1, value2, "periodactiveenddate");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycIsNull() {
            addCriterion("USERMARKETACTIVECYC is null");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycIsNotNull() {
            addCriterion("USERMARKETACTIVECYC is not null");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycEqualTo(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC =", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycNotEqualTo(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC <>", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycGreaterThan(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC >", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC >=", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycLessThan(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC <", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USERMARKETACTIVECYC <=", value, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycIn(List<BigDecimal> values) {
            addCriterion("USERMARKETACTIVECYC in", values, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycNotIn(List<BigDecimal> values) {
            addCriterion("USERMARKETACTIVECYC not in", values, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERMARKETACTIVECYC between", value1, value2, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andUsermarketactivecycNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERMARKETACTIVECYC not between", value1, value2, "usermarketactivecyc");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqIsNull() {
            addCriterion("MERMARKETACTIVEFREQ is null");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqIsNotNull() {
            addCriterion("MERMARKETACTIVEFREQ is not null");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqEqualTo(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ =", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqNotEqualTo(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ <>", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqGreaterThan(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ >", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ >=", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqLessThan(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ <", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MERMARKETACTIVEFREQ <=", value, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqIn(List<BigDecimal> values) {
            addCriterion("MERMARKETACTIVEFREQ in", values, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqNotIn(List<BigDecimal> values) {
            addCriterion("MERMARKETACTIVEFREQ not in", values, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERMARKETACTIVEFREQ between", value1, value2, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andMermarketactivefreqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MERMARKETACTIVEFREQ not between", value1, value2, "mermarketactivefreq");
            return (Criteria) this;
        }

        public Criteria andUserjoincycIsNull() {
            addCriterion("USERJOINCYC is null");
            return (Criteria) this;
        }

        public Criteria andUserjoincycIsNotNull() {
            addCriterion("USERJOINCYC is not null");
            return (Criteria) this;
        }

        public Criteria andUserjoincycEqualTo(BigDecimal value) {
            addCriterion("USERJOINCYC =", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycNotEqualTo(BigDecimal value) {
            addCriterion("USERJOINCYC <>", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycGreaterThan(BigDecimal value) {
            addCriterion("USERJOINCYC >", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USERJOINCYC >=", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycLessThan(BigDecimal value) {
            addCriterion("USERJOINCYC <", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USERJOINCYC <=", value, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycIn(List<BigDecimal> values) {
            addCriterion("USERJOINCYC in", values, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycNotIn(List<BigDecimal> values) {
            addCriterion("USERJOINCYC not in", values, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERJOINCYC between", value1, value2, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andUserjoincycNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERJOINCYC not between", value1, value2, "userjoincyc");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityIsNull() {
            addCriterion("MARKETACTIVEPRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityIsNotNull() {
            addCriterion("MARKETACTIVEPRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityEqualTo(String value) {
            addCriterion("MARKETACTIVEPRIORITY =", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityNotEqualTo(String value) {
            addCriterion("MARKETACTIVEPRIORITY <>", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityGreaterThan(String value) {
            addCriterion("MARKETACTIVEPRIORITY >", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityGreaterThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVEPRIORITY >=", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityLessThan(String value) {
            addCriterion("MARKETACTIVEPRIORITY <", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityLessThanOrEqualTo(String value) {
            addCriterion("MARKETACTIVEPRIORITY <=", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityLike(String value) {
            addCriterion("MARKETACTIVEPRIORITY like", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityNotLike(String value) {
            addCriterion("MARKETACTIVEPRIORITY not like", value, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityIn(List<String> values) {
            addCriterion("MARKETACTIVEPRIORITY in", values, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityNotIn(List<String> values) {
            addCriterion("MARKETACTIVEPRIORITY not in", values, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityBetween(String value1, String value2) {
            addCriterion("MARKETACTIVEPRIORITY between", value1, value2, "marketactivepriority");
            return (Criteria) this;
        }

        public Criteria andMarketactivepriorityNotBetween(String value1, String value2) {
            addCriterion("MARKETACTIVEPRIORITY not between", value1, value2, "marketactivepriority");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketingactivitiesrule
     *
     * @mbggenerated Tue Jun 06 11:01:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}